#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_PropActor_FishingRod

#include "Basic.hpp"

#include "BP_PropActor_FishingRod_classes.hpp"
#include "BP_PropActor_FishingRod_parameters.hpp"


namespace SDK
{

// Function BP_PropActor_FishingRod.BP_PropActor_FishingRod_C.ExecuteUbergraph_BP_PropActor_FishingRod
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_PropActor_FishingRod_C::ExecuteUbergraph_BP_PropActor_FishingRod(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PropActor_FishingRod_C", "ExecuteUbergraph_BP_PropActor_FishingRod");

	Params::BP_PropActor_FishingRod_C_ExecuteUbergraph_BP_PropActor_FishingRod Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_PropActor_FishingRod.BP_PropActor_FishingRod_C.ActivatePhysics
// (Event, Public, BlueprintCallable, BlueprintEvent)

void ABP_PropActor_FishingRod_C::ActivatePhysics()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PropActor_FishingRod_C", "ActivatePhysics");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_PropActor_FishingRod.BP_PropActor_FishingRod_C.OnEnd
// (BlueprintCallable, BlueprintEvent)

void ABP_PropActor_FishingRod_C::OnEnd()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PropActor_FishingRod_C", "OnEnd");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_PropActor_FishingRod.BP_PropActor_FishingRod_C.OnInteractAnimationChanged
// (Event, Protected, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FBFGInteractAnimationData        _newData                                               (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, NoDestructor)
// struct FBFGInteractAnimationData        _oldData                                               (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, NoDestructor)

void ABP_PropActor_FishingRod_C::OnInteractAnimationChanged(const struct FBFGInteractAnimationData& _newData, const struct FBFGInteractAnimationData& _oldData)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PropActor_FishingRod_C", "OnInteractAnimationChanged");

	Params::BP_PropActor_FishingRod_C_OnInteractAnimationChanged Parms{};

	Parms._newData = std::move(_newData);
	Parms._oldData = std::move(_oldData);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_PropActor_FishingRod.BP_PropActor_FishingRod_C.OnStart
// (BlueprintCallable, BlueprintEvent)

void ABP_PropActor_FishingRod_C::OnStart()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PropActor_FishingRod_C", "OnStart");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_PropActor_FishingRod.BP_PropActor_FishingRod_C.OnSwitchedToHighRes
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FBFGInteractAnimationData        _animationData                                         (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, NoDestructor)

void ABP_PropActor_FishingRod_C::OnSwitchedToHighRes(const struct FBFGInteractAnimationData& _animationData)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PropActor_FishingRod_C", "OnSwitchedToHighRes");

	Params::BP_PropActor_FishingRod_C_OnSwitchedToHighRes Parms{};

	Parms._animationData = std::move(_animationData);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_PropActor_FishingRod.BP_PropActor_FishingRod_C.OnSwitchedToLowRes
// (Event, Public, BlueprintCallable, BlueprintEvent)

void ABP_PropActor_FishingRod_C::OnSwitchedToLowRes()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PropActor_FishingRod_C", "OnSwitchedToLowRes");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_PropActor_FishingRod.BP_PropActor_FishingRod_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_PropActor_FishingRod_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PropActor_FishingRod_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}

}

