#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPW_Crosshair_IonDetonator

#include "Basic.hpp"

#include "BPW_Crosshair_IonDetonator_classes.hpp"
#include "BPW_Crosshair_IonDetonator_parameters.hpp"


namespace SDK
{

// Function BPW_Crosshair_IonDetonator.BPW_Crosshair_IonDetonator_C.Get_Bar_IonDetonator_Percent_0
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// float                                   ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

float UBPW_Crosshair_IonDetonator_C::Get_Bar_IonDetonator_Percent_0()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPW_Crosshair_IonDetonator_C", "Get_Bar_IonDetonator_Percent_0");

	Params::BPW_Crosshair_IonDetonator_C_Get_Bar_IonDetonator_Percent_0 Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function BPW_Crosshair_IonDetonator.BPW_Crosshair_IonDetonator_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UBPW_Crosshair_IonDetonator_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPW_Crosshair_IonDetonator_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BPW_Crosshair_IonDetonator.BPW_Crosshair_IonDetonator_C.Tick
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// struct FGeometry                        MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// float                                   InDeltaTime                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBPW_Crosshair_IonDetonator_C::Tick(const struct FGeometry& MyGeometry, float InDeltaTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPW_Crosshair_IonDetonator_C", "Tick");

	Params::BPW_Crosshair_IonDetonator_C_Tick Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.InDeltaTime = InDeltaTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BPW_Crosshair_IonDetonator.BPW_Crosshair_IonDetonator_C.SetCrosshair
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    DetonationCrosshair                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UBPW_Crosshair_IonDetonator_C::SetCrosshair(bool DetonationCrosshair)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPW_Crosshair_IonDetonator_C", "SetCrosshair");

	Params::BPW_Crosshair_IonDetonator_C_SetCrosshair Parms{};

	Parms.DetonationCrosshair = DetonationCrosshair;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BPW_Crosshair_IonDetonator.BPW_Crosshair_IonDetonator_C.WeaponAndAbilitySharedTargetChanged
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    _bNewValue                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UBPW_Crosshair_IonDetonator_C::WeaponAndAbilitySharedTargetChanged(bool _bNewValue)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPW_Crosshair_IonDetonator_C", "WeaponAndAbilitySharedTargetChanged");

	Params::BPW_Crosshair_IonDetonator_C_WeaponAndAbilitySharedTargetChanged Parms{};

	Parms._bNewValue = _bNewValue;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BPW_Crosshair_IonDetonator.BPW_Crosshair_IonDetonator_C.ExecuteUbergraph_BPW_Crosshair_IonDetonator
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBPW_Crosshair_IonDetonator_C::ExecuteUbergraph_BPW_Crosshair_IonDetonator(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPW_Crosshair_IonDetonator_C", "ExecuteUbergraph_BPW_Crosshair_IonDetonator");

	Params::BPW_Crosshair_IonDetonator_C_ExecuteUbergraph_BPW_Crosshair_IonDetonator Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

