#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CH_A05_DesertDevastation

#include "Basic.hpp"

#include "CH_A05_DesertDevastation_classes.hpp"
#include "CH_A05_DesertDevastation_parameters.hpp"


namespace SDK
{

// Function CH_A05_DesertDevastation.CH_A05_DesertDevastation_C.ExecuteUbergraph_CH_A05_DesertDevastation
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UCH_A05_DesertDevastation_C::ExecuteUbergraph_CH_A05_DesertDevastation(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CH_A05_DesertDevastation_C", "ExecuteUbergraph_CH_A05_DesertDevastation");

	Params::CH_A05_DesertDevastation_C_ExecuteUbergraph_CH_A05_DesertDevastation Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function CH_A05_DesertDevastation.CH_A05_DesertDevastation_C.BndEvt__26B1A932-4B2C0ECA-99429680-3DC3031A_BFGK2Node_BoundQuestEvent_0_BFGQuestElement_Event__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UBFGQuest_Element*                _pElement                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UCH_A05_DesertDevastation_C::BndEvt__26B1A932Minus4B2C0ECAMinus99429680Minus3DC3031A_BFGK2Node_BoundQuestEvent_0_BFGQuestElement_Event__DelegateSignature(class UBFGQuest_Element* _pElement)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CH_A05_DesertDevastation_C", "BndEvt__26B1A932-4B2C0ECA-99429680-3DC3031A_BFGK2Node_BoundQuestEvent_0_BFGQuestElement_Event__DelegateSignature");

	Params::CH_A05_DesertDevastation_C_BndEvt__26B1A932Minus4B2C0ECAMinus99429680Minus3DC3031A_BFGK2Node_BoundQuestEvent_0_BFGQuestElement_Event__DelegateSignature Parms{};

	Parms._pElement = _pElement;

	UObject::ProcessEvent(Func, &Parms);
}


// Function CH_A05_DesertDevastation.CH_A05_DesertDevastation_C.BndEvt__26B1A932-4B2C0ECA-99429680-3DC3031A_BFGK2Node_BoundQuestEvent_4_BFGQuestElement_Event__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UBFGQuest_Element*                _pElement                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UCH_A05_DesertDevastation_C::BndEvt__26B1A932Minus4B2C0ECAMinus99429680Minus3DC3031A_BFGK2Node_BoundQuestEvent_4_BFGQuestElement_Event__DelegateSignature(class UBFGQuest_Element* _pElement)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CH_A05_DesertDevastation_C", "BndEvt__26B1A932-4B2C0ECA-99429680-3DC3031A_BFGK2Node_BoundQuestEvent_4_BFGQuestElement_Event__DelegateSignature");

	Params::CH_A05_DesertDevastation_C_BndEvt__26B1A932Minus4B2C0ECAMinus99429680Minus3DC3031A_BFGK2Node_BoundQuestEvent_4_BFGQuestElement_Event__DelegateSignature Parms{};

	Parms._pElement = _pElement;

	UObject::ProcessEvent(Func, &Parms);
}


// Function CH_A05_DesertDevastation.CH_A05_DesertDevastation_C.BndEvt__26B1A932-4B2C0ECA-99429680-3DC3031A_BFGK2Node_BoundQuestEvent_7_BFGQuestElement_Event__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UBFGQuest_Element*                _pElement                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UCH_A05_DesertDevastation_C::BndEvt__26B1A932Minus4B2C0ECAMinus99429680Minus3DC3031A_BFGK2Node_BoundQuestEvent_7_BFGQuestElement_Event__DelegateSignature(class UBFGQuest_Element* _pElement)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CH_A05_DesertDevastation_C", "BndEvt__26B1A932-4B2C0ECA-99429680-3DC3031A_BFGK2Node_BoundQuestEvent_7_BFGQuestElement_Event__DelegateSignature");

	Params::CH_A05_DesertDevastation_C_BndEvt__26B1A932Minus4B2C0ECAMinus99429680Minus3DC3031A_BFGK2Node_BoundQuestEvent_7_BFGQuestElement_Event__DelegateSignature Parms{};

	Parms._pElement = _pElement;

	UObject::ProcessEvent(Func, &Parms);
}


// Function CH_A05_DesertDevastation.CH_A05_DesertDevastation_C.BndEvt__26B1A932-4B2C0ECA-99429680-3DC3031A_BFGK2Node_BoundQuestEvent_9_BFGQuestElement_Event__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UBFGQuest_Element*                _pElement                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UCH_A05_DesertDevastation_C::BndEvt__26B1A932Minus4B2C0ECAMinus99429680Minus3DC3031A_BFGK2Node_BoundQuestEvent_9_BFGQuestElement_Event__DelegateSignature(class UBFGQuest_Element* _pElement)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CH_A05_DesertDevastation_C", "BndEvt__26B1A932-4B2C0ECA-99429680-3DC3031A_BFGK2Node_BoundQuestEvent_9_BFGQuestElement_Event__DelegateSignature");

	Params::CH_A05_DesertDevastation_C_BndEvt__26B1A932Minus4B2C0ECAMinus99429680Minus3DC3031A_BFGK2Node_BoundQuestEvent_9_BFGQuestElement_Event__DelegateSignature Parms{};

	Parms._pElement = _pElement;

	UObject::ProcessEvent(Func, &Parms);
}


// Function CH_A05_DesertDevastation.CH_A05_DesertDevastation_C.BndEvt__2E81FF89-4F6AA698-7106B89F-1D352EAE_BFGK2Node_BoundQuestEvent_0_BFGQuestElement_Event_VandalizeAmountChanged__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UBFGQuest_ElementVandalize*       _Element                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   _NewMonetaryValue                                      (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UCH_A05_DesertDevastation_C::BndEvt__2E81FF89Minus4F6AA698Minus7106B89FMinus1D352EAE_BFGK2Node_BoundQuestEvent_0_BFGQuestElement_Event_VandalizeAmountChanged__DelegateSignature(class UBFGQuest_ElementVandalize* _Element, int32 _NewMonetaryValue)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CH_A05_DesertDevastation_C", "BndEvt__2E81FF89-4F6AA698-7106B89F-1D352EAE_BFGK2Node_BoundQuestEvent_0_BFGQuestElement_Event_VandalizeAmountChanged__DelegateSignature");

	Params::CH_A05_DesertDevastation_C_BndEvt__2E81FF89Minus4F6AA698Minus7106B89FMinus1D352EAE_BFGK2Node_BoundQuestEvent_0_BFGQuestElement_Event_VandalizeAmountChanged__DelegateSignature Parms{};

	Parms._Element = _Element;
	Parms._NewMonetaryValue = _NewMonetaryValue;

	UObject::ProcessEvent(Func, &Parms);
}


// Function CH_A05_DesertDevastation.CH_A05_DesertDevastation_C.BndEvt__489ECE56-447BBC58-AA76D293-C47DB933_BFGK2Node_BoundQuestEvent_3_BFGQuestElement_Event_TimerSubgoalReached__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UBFGQuest_ElementWaitTime*        _Element                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   _Index                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FTimespan                        _TimeLimit                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UCH_A05_DesertDevastation_C::BndEvt__489ECE56Minus447BBC58MinusAA76D293MinusC47DB933_BFGK2Node_BoundQuestEvent_3_BFGQuestElement_Event_TimerSubgoalReached__DelegateSignature(class UBFGQuest_ElementWaitTime* _Element, int32 _Index, const struct FTimespan& _TimeLimit)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CH_A05_DesertDevastation_C", "BndEvt__489ECE56-447BBC58-AA76D293-C47DB933_BFGK2Node_BoundQuestEvent_3_BFGQuestElement_Event_TimerSubgoalReached__DelegateSignature");

	Params::CH_A05_DesertDevastation_C_BndEvt__489ECE56Minus447BBC58MinusAA76D293MinusC47DB933_BFGK2Node_BoundQuestEvent_3_BFGQuestElement_Event_TimerSubgoalReached__DelegateSignature Parms{};

	Parms._Element = _Element;
	Parms._Index = _Index;
	Parms._TimeLimit = std::move(_TimeLimit);

	UObject::ProcessEvent(Func, &Parms);
}


// Function CH_A05_DesertDevastation.CH_A05_DesertDevastation_C.BndEvt__57BEF184-4B0901C1-95FA5C8B-C791707C_BFGK2Node_BoundQuestEvent_2_BFGQuestElement_Event__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UBFGQuest_Element*                _pElement                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UCH_A05_DesertDevastation_C::BndEvt__57BEF184Minus4B0901C1Minus95FA5C8BMinusC791707C_BFGK2Node_BoundQuestEvent_2_BFGQuestElement_Event__DelegateSignature(class UBFGQuest_Element* _pElement)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CH_A05_DesertDevastation_C", "BndEvt__57BEF184-4B0901C1-95FA5C8B-C791707C_BFGK2Node_BoundQuestEvent_2_BFGQuestElement_Event__DelegateSignature");

	Params::CH_A05_DesertDevastation_C_BndEvt__57BEF184Minus4B0901C1Minus95FA5C8BMinusC791707C_BFGK2Node_BoundQuestEvent_2_BFGQuestElement_Event__DelegateSignature Parms{};

	Parms._pElement = _pElement;

	UObject::ProcessEvent(Func, &Parms);
}


// Function CH_A05_DesertDevastation.CH_A05_DesertDevastation_C.BndEvt__97729A73-4C3419F3-DA1CA78C-13B26858_BFGK2Node_BoundQuestEvent_1_BFGQuestElement_Event__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UBFGQuest_Element*                _pElement                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UCH_A05_DesertDevastation_C::BndEvt__97729A73Minus4C3419F3MinusDA1CA78CMinus13B26858_BFGK2Node_BoundQuestEvent_1_BFGQuestElement_Event__DelegateSignature(class UBFGQuest_Element* _pElement)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CH_A05_DesertDevastation_C", "BndEvt__97729A73-4C3419F3-DA1CA78C-13B26858_BFGK2Node_BoundQuestEvent_1_BFGQuestElement_Event__DelegateSignature");

	Params::CH_A05_DesertDevastation_C_BndEvt__97729A73Minus4C3419F3MinusDA1CA78CMinus13B26858_BFGK2Node_BoundQuestEvent_1_BFGQuestElement_Event__DelegateSignature Parms{};

	Parms._pElement = _pElement;

	UObject::ProcessEvent(Func, &Parms);
}


// Function CH_A05_DesertDevastation.CH_A05_DesertDevastation_C.BndEvt__DC88DB1A-476A8E49-4B3AA4BB-31EB8D25_BFGK2Node_BoundQuestEvent_2_BFGQuestElement_Event__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UBFGQuest_Element*                _pElement                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UCH_A05_DesertDevastation_C::BndEvt__DC88DB1AMinus476A8E49Minus4B3AA4BBMinus31EB8D25_BFGK2Node_BoundQuestEvent_2_BFGQuestElement_Event__DelegateSignature(class UBFGQuest_Element* _pElement)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CH_A05_DesertDevastation_C", "BndEvt__DC88DB1A-476A8E49-4B3AA4BB-31EB8D25_BFGK2Node_BoundQuestEvent_2_BFGQuestElement_Event__DelegateSignature");

	Params::CH_A05_DesertDevastation_C_BndEvt__DC88DB1AMinus476A8E49Minus4B3AA4BBMinus31EB8D25_BFGK2Node_BoundQuestEvent_2_BFGQuestElement_Event__DelegateSignature Parms{};

	Parms._pElement = _pElement;

	UObject::ProcessEvent(Func, &Parms);
}

}

