#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BNetQuickAccountModal_UI

#include "Basic.hpp"

#include "Snowfall_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass BNetQuickAccountModal_UI.BNetQuickAccountModal_UI_C
// 0x0000 (0x03B0 - 0x03B0)
class UBNetQuickAccountModal_UI_C final : public USnfBNetQuickAccountModalWidget
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BNetQuickAccountModal_UI_C">();
	}
	static class UBNetQuickAccountModal_UI_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBNetQuickAccountModal_UI_C>();
	}
};
static_assert(alignof(UBNetQuickAccountModal_UI_C) == 0x000008, "Wrong alignment on UBNetQuickAccountModal_UI_C");
static_assert(sizeof(UBNetQuickAccountModal_UI_C) == 0x0003B0, "Wrong size on UBNetQuickAccountModal_UI_C");

}

