#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Item_Rosary_1030_Ether

#include "Basic.hpp"

#include "ItemRosaryBase_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Item_Rosary_1030_Ether.Item_Rosary_1030_Ether_C
// 0x0000 (0x0088 - 0x0088)
class UItem_Rosary_1030_Ether_C final : public UItemRosaryBase_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Item_Rosary_1030_Ether_C">();
	}
	static class UItem_Rosary_1030_Ether_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UItem_Rosary_1030_Ether_C>();
	}
};
static_assert(alignof(UItem_Rosary_1030_Ether_C) == 0x000008, "Wrong alignment on UItem_Rosary_1030_Ether_C");
static_assert(sizeof(UItem_Rosary_1030_Ether_C) == 0x000088, "Wrong size on UItem_Rosary_1030_Ether_C");

}

