#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_TresPlayerStateEventCamera_MikeBowling

#include "Basic.hpp"

#include "TresGame_structs.hpp"
#include "Engine_structs.hpp"
#include "CoreUObject_structs.hpp"


namespace SDK::Params
{

// Function BP_TresPlayerStateEventCamera_MikeBowling.BP_TresPlayerStateEventCamera_MikeBowling_C.ExecuteUbergraph_BP_TresPlayerStateEventCamera_MikeBowling
// 0x112F5920 (0x112F5920 - 0x0000)
struct BP_TresPlayerStateEventCamera_MikeBowling_C_ExecuteUbergraph_BP_TresPlayerStateEventCamera_MikeBowling final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FViewTargetTransitionParamsEx          CallFunc_SetTresCameraTransitionParams_ReturnValue; // 0x0004(0x0014)(NoDestructor)
	int32                                         Temp_int_Variable;                                 // 0x0018(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x001C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_Less_IntInt_ReturnValue2;                 // 0x001D(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1E[0x2];                                       // 0x001E(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0020(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_24[0x4];                                       // 0x0024(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class ATresCameraAnim*                        CallFunc_BP_SpawnTresCameraAnim_ReturnValue;       // 0x0028(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ATresPlayerPawnBase*                    CallFunc_GetLocalTresPlayerPawnBase_ReturnValue;   // 0x0030(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FViewTargetTransitionParamsEx          CallFunc_SetTresCameraTransitionParams_ReturnValue2; // 0x0038(0x0014)(NoDestructor)
	struct FViewTargetTransitionParamsEx          CallFunc_SetTresCameraTransitionParams_ReturnValue3; // 0x004C(0x0014)(NoDestructor)
	class ATresCameraAnim*                        CallFunc_BP_SpawnTresCameraAnim_ReturnValue2;      // 0x0060(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ATresPlayerPawnBase*                    CallFunc_GetLocalTresPlayerPawnBase_ReturnValue2;  // 0x0068(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FViewTargetTransitionParamsEx          CallFunc_SetTresCameraTransitionParams_ReturnValue4; // 0x0070(0x0014)(NoDestructor)
	struct FViewTargetTransitionParamsEx          CallFunc_SetTresCameraTransitionParams_ReturnValue5; // 0x0084(0x0014)(NoDestructor)
	bool                                          Temp_bool_Has_Been_Initd_Variable;                 // 0x0098(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_99[0x3];                                       // 0x0099(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Temp_int_Variable2;                                // 0x009C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_IsClosed_Variable;                       // 0x00A0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_Less_IntInt_ReturnValue3;                 // 0x00A1(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_Less_IntInt_ReturnValue4;                 // 0x00A2(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_A3[0x1];                                       // 0x00A3(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Add_IntInt_ReturnValue2;                  // 0x00A4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FTresScreenBlurParams                  K2Node_MakeStruct_TresScreenBlurParams;            // 0x00A8(0x112E95F0)(NoDestructor)
	class APlayerController*                      CallFunc_GetLocalPlayerController_ReturnValue;     // 0x00F8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Has_Been_Initd_Variable2;                // 0x0100(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_101[0x7];                                      // 0x0101(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class APlayerController*                      CallFunc_GetLocalPlayerController_ReturnValue2;    // 0x0108(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class APlayerController*                      CallFunc_GetLocalPlayerController_ReturnValue3;    // 0x0110(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Variable3;                                // 0x0118(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue5;                 // 0x011C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_Less_IntInt_ReturnValue6;                 // 0x011D(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_11E[0x2];                                      // 0x011E(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Add_IntInt_ReturnValue3;                  // 0x0120(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_IsClosed_Variable2;                      // 0x0124(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_125[0x3];                                      // 0x0125(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class ATresPlayerPawnBase*                    CallFunc_GetLocalTresPlayerPawnBase_ReturnValue3;  // 0x0128(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_K2_GetActorLocation_ReturnValue;          // 0x0130(0x000C)(IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_13C[0x4];                                      // 0x013C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTransform                             CallFunc_GetTransform_ReturnValue;                 // 0x0140(0x112E9D50)(IsPlainOldData, NoDestructor)
	struct FVector                                CallFunc_Add_VectorVector_ReturnValue;             // 0x0170(0x000C)(IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_TransformLocation_ReturnValue;            // 0x017C(0x000C)(IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ATresCameraAnim*                        CallFunc_BP_SpawnTresCameraAnim_ReturnValue3;      // 0x0188(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ATresPlayerPawnBase*                    CallFunc_GetLocalTresPlayerPawnBase_ReturnValue4;  // 0x0190(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FViewTargetTransitionParamsEx          CallFunc_SetTresCameraTransitionParams_ReturnValue6; // 0x0198(0x0014)(NoDestructor)
	struct FViewTargetTransitionParamsEx          CallFunc_SetTresCameraTransitionParams_ReturnValue7; // 0x01AC(0x0014)(NoDestructor)
	class ATresPlayerControllerBase*              CallFunc_GetLocalTresPlayerControllerBase_ReturnValue; // 0x01C0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ATresGameState*                         CallFunc_GetTresGameState_ReturnValue;             // 0x01C8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ATresGameState*                         CallFunc_GetTresGameState_ReturnValue2;            // 0x01D0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ATresSceneManager*                      CallFunc_GetSceneManager_ReturnValue;              // 0x01D8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ATresSceneManager*                      CallFunc_GetSceneManager_ReturnValue2;             // 0x01E0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ETresPlayerSpecificActionID                   K2Node_Event_ActionID;                             // 0x01E8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1E9[0x3];                                      // 0x01E9(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         K2Node_Event_SubID;                                // 0x01EC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ATresPlayerPawnBase*                    CallFunc_GetLocalTresPlayerPawnBase_ReturnValue5;  // 0x01F0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_SwitchEnum_CmpSuccess;                      // 0x01F8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1F9[0x7];                                      // 0x01F9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class ATresCharPawnBase*                      CallFunc_GetSpecificActionAccompanyPawn_ReturnValue; // 0x0200(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ETresStateID                                  CallFunc_GetStateID_ReturnValue;                   // 0x0208(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_SwitchEnum2_CmpSuccess;                     // 0x0209(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_20A[0x6];                                      // 0x020A(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class ATresCharPawnBase*                      K2Node_Event_SendActor;                            // 0x0210(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   K2Node_Event_AnimSeqName;                          // 0x0218(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ETresAnimNotifyBpEventID                      K2Node_Event_EventID;                              // 0x0220(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_221[0x3];                                      // 0x0221(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         K2Node_Event_Param;                                // 0x0224(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_NameName_ReturnValue;          // 0x0228(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_EqualEqual_NameName_ReturnValue2;         // 0x0229(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_22A[0x6];                                      // 0x022A(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class ATresPlayerPawnBase*                    CallFunc_GetLocalTresPlayerPawnBase_ReturnValue6;  // 0x0230(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_ObjectObject_ReturnValue;      // 0x0238(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_239[0x3];                                      // 0x0239(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FViewTargetTransitionParamsEx          CallFunc_SetTresCameraTransitionParams_ReturnValue8; // 0x023C(0x0014)(NoDestructor)
	bool                                          Temp_bool_Has_Been_Initd_Variable3;                // 0x0250(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          Temp_bool_IsClosed_Variable3;                      // 0x0251(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	ETresStateID                                  K2Node_Event_StateID;                              // 0x0252(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_253[0x5];                                      // 0x0253(0x0005)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class AActor*>                         Temp_object_Variable;                              // 0x0258(0x0010)(ZeroConstructor, ReferenceParm)
	bool                                          K2Node_SwitchEnum3_CmpSuccess;                     // 0x0268(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_269[0x7];                                      // 0x0269(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FHitResult                             CallFunc_BP_TresLineTraceByChannel_OutHit;         // 0x0270(0x112F5920)(IsPlainOldData, NoDestructor, ContainsInstancedReference)
	bool                                          CallFunc_BP_TresLineTraceByChannel_ReturnValue;    // 0x02F8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_2F9[0x3];                                      // 0x02F9(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTresScreenBlurParams                  K2Node_MakeStruct_TresScreenBlurParams2;           // 0x02FC(0x112E95F0)(NoDestructor)
};
static_assert(alignof(BP_TresPlayerStateEventCamera_MikeBowling_C_ExecuteUbergraph_BP_TresPlayerStateEventCamera_MikeBowling) == 0x112F5920, "Wrong alignment on BP_TresPlayerStateEventCamera_MikeBowling_C_ExecuteUbergraph_BP_TresPlayerStateEventCamera_MikeBowling");
static_assert(sizeof(BP_TresPlayerStateEventCamera_MikeBowling_C_ExecuteUbergraph_BP_TresPlayerStateEventCamera_MikeBowling) == 0x112F5920, "Wrong size on BP_TresPlayerStateEventCamera_MikeBowling_C_ExecuteUbergraph_BP_TresPlayerStateEventCamera_MikeBowling");
static_assert(offsetof(BP_TresPlayerStateEventCamera_MikeBowling_C_ExecuteUbergraph_BP_TresPlayerStateEventCamera_MikeBowling, EntryPoint) == 0x000000, "Member 'BP_TresPlayerStateEventCamera_MikeBowling_C_ExecuteUbergraph_BP_TresPlayerStateEventCamera_MikeBowling::EntryPoint' has a wrong offset!");
static_assert(offsetof(BP_TresPlayerStateEventCamera_MikeBowling_C_ExecuteUbergraph_BP_TresPlayerStateEventCamera_MikeBowling, CallFunc_SetTresCameraTransitionParams_ReturnValue) == 0x000004, "Member 'BP_TresPlayerStateEventCamera_MikeBowling_C_ExecuteUbergraph_BP_TresPlayerStateEventCamera_MikeBowling::CallFunc_SetTresCameraTransitionParams_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_TresPlayerStateEventCamera_MikeBowling_C_ExecuteUbergraph_BP_TresPlayerStateEventCamera_MikeBowling, Temp_int_Variable) == 0x000018, "Member 'BP_TresPlayerStateEventCamera_MikeBowling_C_ExecuteUbergraph_BP_TresPlayerStateEventCamera_MikeBowling::Temp_int_Variable' has a wrong offset!");
static_assert(offsetof(BP_TresPlayerStateEventCamera_MikeBowling_C_ExecuteUbergraph_BP_TresPlayerStateEventCamera_MikeBowling, CallFunc_Less_IntInt_ReturnValue) == 0x00001C, "Member 'BP_TresPlayerStateEventCamera_MikeBowling_C_ExecuteUbergraph_BP_TresPlayerStateEventCamera_MikeBowling::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_TresPlayerStateEventCamera_MikeBowling_C_ExecuteUbergraph_BP_TresPlayerStateEventCamera_MikeBowling, CallFunc_Less_IntInt_ReturnValue2) == 0x00001D, "Member 'BP_TresPlayerStateEventCamera_MikeBowling_C_ExecuteUbergraph_BP_TresPlayerStateEventCamera_MikeBowling::CallFunc_Less_IntInt_ReturnValue2' has a wrong offset!");
static_assert(offsetof(BP_TresPlayerStateEventCamera_MikeBowling_C_ExecuteUbergraph_BP_TresPlayerStateEventCamera_MikeBowling, CallFunc_Add_IntInt_ReturnValue) == 0x000020, "Member 'BP_TresPlayerStateEventCamera_MikeBowling_C_ExecuteUbergraph_BP_TresPlayerStateEventCamera_MikeBowling::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_TresPlayerStateEventCamera_MikeBowling_C_ExecuteUbergraph_BP_TresPlayerStateEventCamera_MikeBowling, CallFunc_BP_SpawnTresCameraAnim_ReturnValue) == 0x000028, "Member 'BP_TresPlayerStateEventCamera_MikeBowling_C_ExecuteUbergraph_BP_TresPlayerStateEventCamera_MikeBowling::CallFunc_BP_SpawnTresCameraAnim_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_TresPlayerStateEventCamera_MikeBowling_C_ExecuteUbergraph_BP_TresPlayerStateEventCamera_MikeBowling, CallFunc_GetLocalTresPlayerPawnBase_ReturnValue) == 0x000030, "Member 'BP_TresPlayerStateEventCamera_MikeBowling_C_ExecuteUbergraph_BP_TresPlayerStateEventCamera_MikeBowling::CallFunc_GetLocalTresPlayerPawnBase_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_TresPlayerStateEventCamera_MikeBowling_C_ExecuteUbergraph_BP_TresPlayerStateEventCamera_MikeBowling, CallFunc_SetTresCameraTransitionParams_ReturnValue2) == 0x000038, "Member 'BP_TresPlayerStateEventCamera_MikeBowling_C_ExecuteUbergraph_BP_TresPlayerStateEventCamera_MikeBowling::CallFunc_SetTresCameraTransitionParams_ReturnValue2' has a wrong offset!");
static_assert(offsetof(BP_TresPlayerStateEventCamera_MikeBowling_C_ExecuteUbergraph_BP_TresPlayerStateEventCamera_MikeBowling, CallFunc_SetTresCameraTransitionParams_ReturnValue3) == 0x00004C, "Member 'BP_TresPlayerStateEventCamera_MikeBowling_C_ExecuteUbergraph_BP_TresPlayerStateEventCamera_MikeBowling::CallFunc_SetTresCameraTransitionParams_ReturnValue3' has a wrong offset!");
static_assert(offsetof(BP_TresPlayerStateEventCamera_MikeBowling_C_ExecuteUbergraph_BP_TresPlayerStateEventCamera_MikeBowling, CallFunc_BP_SpawnTresCameraAnim_ReturnValue2) == 0x000060, "Member 'BP_TresPlayerStateEventCamera_MikeBowling_C_ExecuteUbergraph_BP_TresPlayerStateEventCamera_MikeBowling::CallFunc_BP_SpawnTresCameraAnim_ReturnValue2' has a wrong offset!");
static_assert(offsetof(BP_TresPlayerStateEventCamera_MikeBowling_C_ExecuteUbergraph_BP_TresPlayerStateEventCamera_MikeBowling, CallFunc_GetLocalTresPlayerPawnBase_ReturnValue2) == 0x000068, "Member 'BP_TresPlayerStateEventCamera_MikeBowling_C_ExecuteUbergraph_BP_TresPlayerStateEventCamera_MikeBowling::CallFunc_GetLocalTresPlayerPawnBase_ReturnValue2' has a wrong offset!");
static_assert(offsetof(BP_TresPlayerStateEventCamera_MikeBowling_C_ExecuteUbergraph_BP_TresPlayerStateEventCamera_MikeBowling, CallFunc_SetTresCameraTransitionParams_ReturnValue4) == 0x000070, "Member 'BP_TresPlayerStateEventCamera_MikeBowling_C_ExecuteUbergraph_BP_TresPlayerStateEventCamera_MikeBowling::CallFunc_SetTresCameraTransitionParams_ReturnValue4' has a wrong offset!");
static_assert(offsetof(BP_TresPlayerStateEventCamera_MikeBowling_C_ExecuteUbergraph_BP_TresPlayerStateEventCamera_MikeBowling, CallFunc_SetTresCameraTransitionParams_ReturnValue5) == 0x000084, "Member 'BP_TresPlayerStateEventCamera_MikeBowling_C_ExecuteUbergraph_BP_TresPlayerStateEventCamera_MikeBowling::CallFunc_SetTresCameraTransitionParams_ReturnValue5' has a wrong offset!");
static_assert(offsetof(BP_TresPlayerStateEventCamera_MikeBowling_C_ExecuteUbergraph_BP_TresPlayerStateEventCamera_MikeBowling, Temp_bool_Has_Been_Initd_Variable) == 0x000098, "Member 'BP_TresPlayerStateEventCamera_MikeBowling_C_ExecuteUbergraph_BP_TresPlayerStateEventCamera_MikeBowling::Temp_bool_Has_Been_Initd_Variable' has a wrong offset!");
static_assert(offsetof(BP_TresPlayerStateEventCamera_MikeBowling_C_ExecuteUbergraph_BP_TresPlayerStateEventCamera_MikeBowling, Temp_int_Variable2) == 0x00009C, "Member 'BP_TresPlayerStateEventCamera_MikeBowling_C_ExecuteUbergraph_BP_TresPlayerStateEventCamera_MikeBowling::Temp_int_Variable2' has a wrong offset!");
static_assert(offsetof(BP_TresPlayerStateEventCamera_MikeBowling_C_ExecuteUbergraph_BP_TresPlayerStateEventCamera_MikeBowling, Temp_bool_IsClosed_Variable) == 0x0000A0, "Member 'BP_TresPlayerStateEventCamera_MikeBowling_C_ExecuteUbergraph_BP_TresPlayerStateEventCamera_MikeBowling::Temp_bool_IsClosed_Variable' has a wrong offset!");
static_assert(offsetof(BP_TresPlayerStateEventCamera_MikeBowling_C_ExecuteUbergraph_BP_TresPlayerStateEventCamera_MikeBowling, CallFunc_Less_IntInt_ReturnValue3) == 0x0000A1, "Member 'BP_TresPlayerStateEventCamera_MikeBowling_C_ExecuteUbergraph_BP_TresPlayerStateEventCamera_MikeBowling::CallFunc_Less_IntInt_ReturnValue3' has a wrong offset!");
static_assert(offsetof(BP_TresPlayerStateEventCamera_MikeBowling_C_ExecuteUbergraph_BP_TresPlayerStateEventCamera_MikeBowling, CallFunc_Less_IntInt_ReturnValue4) == 0x0000A2, "Member 'BP_TresPlayerStateEventCamera_MikeBowling_C_ExecuteUbergraph_BP_TresPlayerStateEventCamera_MikeBowling::CallFunc_Less_IntInt_ReturnValue4' has a wrong offset!");
static_assert(offsetof(BP_TresPlayerStateEventCamera_MikeBowling_C_ExecuteUbergraph_BP_TresPlayerStateEventCamera_MikeBowling, CallFunc_Add_IntInt_ReturnValue2) == 0x0000A4, "Member 'BP_TresPlayerStateEventCamera_MikeBowling_C_ExecuteUbergraph_BP_TresPlayerStateEventCamera_MikeBowling::CallFunc_Add_IntInt_ReturnValue2' has a wrong offset!");
static_assert(offsetof(BP_TresPlayerStateEventCamera_MikeBowling_C_ExecuteUbergraph_BP_TresPlayerStateEventCamera_MikeBowling, K2Node_MakeStruct_TresScreenBlurParams) == 0x0000A8, "Member 'BP_TresPlayerStateEventCamera_MikeBowling_C_ExecuteUbergraph_BP_TresPlayerStateEventCamera_MikeBowling::K2Node_MakeStruct_TresScreenBlurParams' has a wrong offset!");
static_assert(offsetof(BP_TresPlayerStateEventCamera_MikeBowling_C_ExecuteUbergraph_BP_TresPlayerStateEventCamera_MikeBowling, CallFunc_GetLocalPlayerController_ReturnValue) == 0x0000F8, "Member 'BP_TresPlayerStateEventCamera_MikeBowling_C_ExecuteUbergraph_BP_TresPlayerStateEventCamera_MikeBowling::CallFunc_GetLocalPlayerController_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_TresPlayerStateEventCamera_MikeBowling_C_ExecuteUbergraph_BP_TresPlayerStateEventCamera_MikeBowling, Temp_bool_Has_Been_Initd_Variable2) == 0x000100, "Member 'BP_TresPlayerStateEventCamera_MikeBowling_C_ExecuteUbergraph_BP_TresPlayerStateEventCamera_MikeBowling::Temp_bool_Has_Been_Initd_Variable2' has a wrong offset!");
static_assert(offsetof(BP_TresPlayerStateEventCamera_MikeBowling_C_ExecuteUbergraph_BP_TresPlayerStateEventCamera_MikeBowling, CallFunc_GetLocalPlayerController_ReturnValue2) == 0x000108, "Member 'BP_TresPlayerStateEventCamera_MikeBowling_C_ExecuteUbergraph_BP_TresPlayerStateEventCamera_MikeBowling::CallFunc_GetLocalPlayerController_ReturnValue2' has a wrong offset!");
static_assert(offsetof(BP_TresPlayerStateEventCamera_MikeBowling_C_ExecuteUbergraph_BP_TresPlayerStateEventCamera_MikeBowling, CallFunc_GetLocalPlayerController_ReturnValue3) == 0x000110, "Member 'BP_TresPlayerStateEventCamera_MikeBowling_C_ExecuteUbergraph_BP_TresPlayerStateEventCamera_MikeBowling::CallFunc_GetLocalPlayerController_ReturnValue3' has a wrong offset!");
static_assert(offsetof(BP_TresPlayerStateEventCamera_MikeBowling_C_ExecuteUbergraph_BP_TresPlayerStateEventCamera_MikeBowling, Temp_int_Variable3) == 0x000118, "Member 'BP_TresPlayerStateEventCamera_MikeBowling_C_ExecuteUbergraph_BP_TresPlayerStateEventCamera_MikeBowling::Temp_int_Variable3' has a wrong offset!");
static_assert(offsetof(BP_TresPlayerStateEventCamera_MikeBowling_C_ExecuteUbergraph_BP_TresPlayerStateEventCamera_MikeBowling, CallFunc_Less_IntInt_ReturnValue5) == 0x00011C, "Member 'BP_TresPlayerStateEventCamera_MikeBowling_C_ExecuteUbergraph_BP_TresPlayerStateEventCamera_MikeBowling::CallFunc_Less_IntInt_ReturnValue5' has a wrong offset!");
static_assert(offsetof(BP_TresPlayerStateEventCamera_MikeBowling_C_ExecuteUbergraph_BP_TresPlayerStateEventCamera_MikeBowling, CallFunc_Less_IntInt_ReturnValue6) == 0x00011D, "Member 'BP_TresPlayerStateEventCamera_MikeBowling_C_ExecuteUbergraph_BP_TresPlayerStateEventCamera_MikeBowling::CallFunc_Less_IntInt_ReturnValue6' has a wrong offset!");
static_assert(offsetof(BP_TresPlayerStateEventCamera_MikeBowling_C_ExecuteUbergraph_BP_TresPlayerStateEventCamera_MikeBowling, CallFunc_Add_IntInt_ReturnValue3) == 0x000120, "Member 'BP_TresPlayerStateEventCamera_MikeBowling_C_ExecuteUbergraph_BP_TresPlayerStateEventCamera_MikeBowling::CallFunc_Add_IntInt_ReturnValue3' has a wrong offset!");
static_assert(offsetof(BP_TresPlayerStateEventCamera_MikeBowling_C_ExecuteUbergraph_BP_TresPlayerStateEventCamera_MikeBowling, Temp_bool_IsClosed_Variable2) == 0x000124, "Member 'BP_TresPlayerStateEventCamera_MikeBowling_C_ExecuteUbergraph_BP_TresPlayerStateEventCamera_MikeBowling::Temp_bool_IsClosed_Variable2' has a wrong offset!");
static_assert(offsetof(BP_TresPlayerStateEventCamera_MikeBowling_C_ExecuteUbergraph_BP_TresPlayerStateEventCamera_MikeBowling, CallFunc_GetLocalTresPlayerPawnBase_ReturnValue3) == 0x000128, "Member 'BP_TresPlayerStateEventCamera_MikeBowling_C_ExecuteUbergraph_BP_TresPlayerStateEventCamera_MikeBowling::CallFunc_GetLocalTresPlayerPawnBase_ReturnValue3' has a wrong offset!");
static_assert(offsetof(BP_TresPlayerStateEventCamera_MikeBowling_C_ExecuteUbergraph_BP_TresPlayerStateEventCamera_MikeBowling, CallFunc_K2_GetActorLocation_ReturnValue) == 0x000130, "Member 'BP_TresPlayerStateEventCamera_MikeBowling_C_ExecuteUbergraph_BP_TresPlayerStateEventCamera_MikeBowling::CallFunc_K2_GetActorLocation_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_TresPlayerStateEventCamera_MikeBowling_C_ExecuteUbergraph_BP_TresPlayerStateEventCamera_MikeBowling, CallFunc_GetTransform_ReturnValue) == 0x000140, "Member 'BP_TresPlayerStateEventCamera_MikeBowling_C_ExecuteUbergraph_BP_TresPlayerStateEventCamera_MikeBowling::CallFunc_GetTransform_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_TresPlayerStateEventCamera_MikeBowling_C_ExecuteUbergraph_BP_TresPlayerStateEventCamera_MikeBowling, CallFunc_Add_VectorVector_ReturnValue) == 0x000170, "Member 'BP_TresPlayerStateEventCamera_MikeBowling_C_ExecuteUbergraph_BP_TresPlayerStateEventCamera_MikeBowling::CallFunc_Add_VectorVector_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_TresPlayerStateEventCamera_MikeBowling_C_ExecuteUbergraph_BP_TresPlayerStateEventCamera_MikeBowling, CallFunc_TransformLocation_ReturnValue) == 0x00017C, "Member 'BP_TresPlayerStateEventCamera_MikeBowling_C_ExecuteUbergraph_BP_TresPlayerStateEventCamera_MikeBowling::CallFunc_TransformLocation_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_TresPlayerStateEventCamera_MikeBowling_C_ExecuteUbergraph_BP_TresPlayerStateEventCamera_MikeBowling, CallFunc_BP_SpawnTresCameraAnim_ReturnValue3) == 0x000188, "Member 'BP_TresPlayerStateEventCamera_MikeBowling_C_ExecuteUbergraph_BP_TresPlayerStateEventCamera_MikeBowling::CallFunc_BP_SpawnTresCameraAnim_ReturnValue3' has a wrong offset!");
static_assert(offsetof(BP_TresPlayerStateEventCamera_MikeBowling_C_ExecuteUbergraph_BP_TresPlayerStateEventCamera_MikeBowling, CallFunc_GetLocalTresPlayerPawnBase_ReturnValue4) == 0x000190, "Member 'BP_TresPlayerStateEventCamera_MikeBowling_C_ExecuteUbergraph_BP_TresPlayerStateEventCamera_MikeBowling::CallFunc_GetLocalTresPlayerPawnBase_ReturnValue4' has a wrong offset!");
static_assert(offsetof(BP_TresPlayerStateEventCamera_MikeBowling_C_ExecuteUbergraph_BP_TresPlayerStateEventCamera_MikeBowling, CallFunc_SetTresCameraTransitionParams_ReturnValue6) == 0x000198, "Member 'BP_TresPlayerStateEventCamera_MikeBowling_C_ExecuteUbergraph_BP_TresPlayerStateEventCamera_MikeBowling::CallFunc_SetTresCameraTransitionParams_ReturnValue6' has a wrong offset!");
static_assert(offsetof(BP_TresPlayerStateEventCamera_MikeBowling_C_ExecuteUbergraph_BP_TresPlayerStateEventCamera_MikeBowling, CallFunc_SetTresCameraTransitionParams_ReturnValue7) == 0x0001AC, "Member 'BP_TresPlayerStateEventCamera_MikeBowling_C_ExecuteUbergraph_BP_TresPlayerStateEventCamera_MikeBowling::CallFunc_SetTresCameraTransitionParams_ReturnValue7' has a wrong offset!");
static_assert(offsetof(BP_TresPlayerStateEventCamera_MikeBowling_C_ExecuteUbergraph_BP_TresPlayerStateEventCamera_MikeBowling, CallFunc_GetLocalTresPlayerControllerBase_ReturnValue) == 0x0001C0, "Member 'BP_TresPlayerStateEventCamera_MikeBowling_C_ExecuteUbergraph_BP_TresPlayerStateEventCamera_MikeBowling::CallFunc_GetLocalTresPlayerControllerBase_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_TresPlayerStateEventCamera_MikeBowling_C_ExecuteUbergraph_BP_TresPlayerStateEventCamera_MikeBowling, CallFunc_GetTresGameState_ReturnValue) == 0x0001C8, "Member 'BP_TresPlayerStateEventCamera_MikeBowling_C_ExecuteUbergraph_BP_TresPlayerStateEventCamera_MikeBowling::CallFunc_GetTresGameState_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_TresPlayerStateEventCamera_MikeBowling_C_ExecuteUbergraph_BP_TresPlayerStateEventCamera_MikeBowling, CallFunc_GetTresGameState_ReturnValue2) == 0x0001D0, "Member 'BP_TresPlayerStateEventCamera_MikeBowling_C_ExecuteUbergraph_BP_TresPlayerStateEventCamera_MikeBowling::CallFunc_GetTresGameState_ReturnValue2' has a wrong offset!");
static_assert(offsetof(BP_TresPlayerStateEventCamera_MikeBowling_C_ExecuteUbergraph_BP_TresPlayerStateEventCamera_MikeBowling, CallFunc_GetSceneManager_ReturnValue) == 0x0001D8, "Member 'BP_TresPlayerStateEventCamera_MikeBowling_C_ExecuteUbergraph_BP_TresPlayerStateEventCamera_MikeBowling::CallFunc_GetSceneManager_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_TresPlayerStateEventCamera_MikeBowling_C_ExecuteUbergraph_BP_TresPlayerStateEventCamera_MikeBowling, CallFunc_GetSceneManager_ReturnValue2) == 0x0001E0, "Member 'BP_TresPlayerStateEventCamera_MikeBowling_C_ExecuteUbergraph_BP_TresPlayerStateEventCamera_MikeBowling::CallFunc_GetSceneManager_ReturnValue2' has a wrong offset!");
static_assert(offsetof(BP_TresPlayerStateEventCamera_MikeBowling_C_ExecuteUbergraph_BP_TresPlayerStateEventCamera_MikeBowling, K2Node_Event_ActionID) == 0x0001E8, "Member 'BP_TresPlayerStateEventCamera_MikeBowling_C_ExecuteUbergraph_BP_TresPlayerStateEventCamera_MikeBowling::K2Node_Event_ActionID' has a wrong offset!");
static_assert(offsetof(BP_TresPlayerStateEventCamera_MikeBowling_C_ExecuteUbergraph_BP_TresPlayerStateEventCamera_MikeBowling, K2Node_Event_SubID) == 0x0001EC, "Member 'BP_TresPlayerStateEventCamera_MikeBowling_C_ExecuteUbergraph_BP_TresPlayerStateEventCamera_MikeBowling::K2Node_Event_SubID' has a wrong offset!");
static_assert(offsetof(BP_TresPlayerStateEventCamera_MikeBowling_C_ExecuteUbergraph_BP_TresPlayerStateEventCamera_MikeBowling, CallFunc_GetLocalTresPlayerPawnBase_ReturnValue5) == 0x0001F0, "Member 'BP_TresPlayerStateEventCamera_MikeBowling_C_ExecuteUbergraph_BP_TresPlayerStateEventCamera_MikeBowling::CallFunc_GetLocalTresPlayerPawnBase_ReturnValue5' has a wrong offset!");
static_assert(offsetof(BP_TresPlayerStateEventCamera_MikeBowling_C_ExecuteUbergraph_BP_TresPlayerStateEventCamera_MikeBowling, K2Node_SwitchEnum_CmpSuccess) == 0x0001F8, "Member 'BP_TresPlayerStateEventCamera_MikeBowling_C_ExecuteUbergraph_BP_TresPlayerStateEventCamera_MikeBowling::K2Node_SwitchEnum_CmpSuccess' has a wrong offset!");
static_assert(offsetof(BP_TresPlayerStateEventCamera_MikeBowling_C_ExecuteUbergraph_BP_TresPlayerStateEventCamera_MikeBowling, CallFunc_GetSpecificActionAccompanyPawn_ReturnValue) == 0x000200, "Member 'BP_TresPlayerStateEventCamera_MikeBowling_C_ExecuteUbergraph_BP_TresPlayerStateEventCamera_MikeBowling::CallFunc_GetSpecificActionAccompanyPawn_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_TresPlayerStateEventCamera_MikeBowling_C_ExecuteUbergraph_BP_TresPlayerStateEventCamera_MikeBowling, CallFunc_GetStateID_ReturnValue) == 0x000208, "Member 'BP_TresPlayerStateEventCamera_MikeBowling_C_ExecuteUbergraph_BP_TresPlayerStateEventCamera_MikeBowling::CallFunc_GetStateID_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_TresPlayerStateEventCamera_MikeBowling_C_ExecuteUbergraph_BP_TresPlayerStateEventCamera_MikeBowling, K2Node_SwitchEnum2_CmpSuccess) == 0x000209, "Member 'BP_TresPlayerStateEventCamera_MikeBowling_C_ExecuteUbergraph_BP_TresPlayerStateEventCamera_MikeBowling::K2Node_SwitchEnum2_CmpSuccess' has a wrong offset!");
static_assert(offsetof(BP_TresPlayerStateEventCamera_MikeBowling_C_ExecuteUbergraph_BP_TresPlayerStateEventCamera_MikeBowling, K2Node_Event_SendActor) == 0x000210, "Member 'BP_TresPlayerStateEventCamera_MikeBowling_C_ExecuteUbergraph_BP_TresPlayerStateEventCamera_MikeBowling::K2Node_Event_SendActor' has a wrong offset!");
static_assert(offsetof(BP_TresPlayerStateEventCamera_MikeBowling_C_ExecuteUbergraph_BP_TresPlayerStateEventCamera_MikeBowling, K2Node_Event_AnimSeqName) == 0x000218, "Member 'BP_TresPlayerStateEventCamera_MikeBowling_C_ExecuteUbergraph_BP_TresPlayerStateEventCamera_MikeBowling::K2Node_Event_AnimSeqName' has a wrong offset!");
static_assert(offsetof(BP_TresPlayerStateEventCamera_MikeBowling_C_ExecuteUbergraph_BP_TresPlayerStateEventCamera_MikeBowling, K2Node_Event_EventID) == 0x000220, "Member 'BP_TresPlayerStateEventCamera_MikeBowling_C_ExecuteUbergraph_BP_TresPlayerStateEventCamera_MikeBowling::K2Node_Event_EventID' has a wrong offset!");
static_assert(offsetof(BP_TresPlayerStateEventCamera_MikeBowling_C_ExecuteUbergraph_BP_TresPlayerStateEventCamera_MikeBowling, K2Node_Event_Param) == 0x000224, "Member 'BP_TresPlayerStateEventCamera_MikeBowling_C_ExecuteUbergraph_BP_TresPlayerStateEventCamera_MikeBowling::K2Node_Event_Param' has a wrong offset!");
static_assert(offsetof(BP_TresPlayerStateEventCamera_MikeBowling_C_ExecuteUbergraph_BP_TresPlayerStateEventCamera_MikeBowling, CallFunc_EqualEqual_NameName_ReturnValue) == 0x000228, "Member 'BP_TresPlayerStateEventCamera_MikeBowling_C_ExecuteUbergraph_BP_TresPlayerStateEventCamera_MikeBowling::CallFunc_EqualEqual_NameName_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_TresPlayerStateEventCamera_MikeBowling_C_ExecuteUbergraph_BP_TresPlayerStateEventCamera_MikeBowling, CallFunc_EqualEqual_NameName_ReturnValue2) == 0x000229, "Member 'BP_TresPlayerStateEventCamera_MikeBowling_C_ExecuteUbergraph_BP_TresPlayerStateEventCamera_MikeBowling::CallFunc_EqualEqual_NameName_ReturnValue2' has a wrong offset!");
static_assert(offsetof(BP_TresPlayerStateEventCamera_MikeBowling_C_ExecuteUbergraph_BP_TresPlayerStateEventCamera_MikeBowling, CallFunc_GetLocalTresPlayerPawnBase_ReturnValue6) == 0x000230, "Member 'BP_TresPlayerStateEventCamera_MikeBowling_C_ExecuteUbergraph_BP_TresPlayerStateEventCamera_MikeBowling::CallFunc_GetLocalTresPlayerPawnBase_ReturnValue6' has a wrong offset!");
static_assert(offsetof(BP_TresPlayerStateEventCamera_MikeBowling_C_ExecuteUbergraph_BP_TresPlayerStateEventCamera_MikeBowling, CallFunc_EqualEqual_ObjectObject_ReturnValue) == 0x000238, "Member 'BP_TresPlayerStateEventCamera_MikeBowling_C_ExecuteUbergraph_BP_TresPlayerStateEventCamera_MikeBowling::CallFunc_EqualEqual_ObjectObject_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_TresPlayerStateEventCamera_MikeBowling_C_ExecuteUbergraph_BP_TresPlayerStateEventCamera_MikeBowling, CallFunc_SetTresCameraTransitionParams_ReturnValue8) == 0x00023C, "Member 'BP_TresPlayerStateEventCamera_MikeBowling_C_ExecuteUbergraph_BP_TresPlayerStateEventCamera_MikeBowling::CallFunc_SetTresCameraTransitionParams_ReturnValue8' has a wrong offset!");
static_assert(offsetof(BP_TresPlayerStateEventCamera_MikeBowling_C_ExecuteUbergraph_BP_TresPlayerStateEventCamera_MikeBowling, Temp_bool_Has_Been_Initd_Variable3) == 0x000250, "Member 'BP_TresPlayerStateEventCamera_MikeBowling_C_ExecuteUbergraph_BP_TresPlayerStateEventCamera_MikeBowling::Temp_bool_Has_Been_Initd_Variable3' has a wrong offset!");
static_assert(offsetof(BP_TresPlayerStateEventCamera_MikeBowling_C_ExecuteUbergraph_BP_TresPlayerStateEventCamera_MikeBowling, Temp_bool_IsClosed_Variable3) == 0x000251, "Member 'BP_TresPlayerStateEventCamera_MikeBowling_C_ExecuteUbergraph_BP_TresPlayerStateEventCamera_MikeBowling::Temp_bool_IsClosed_Variable3' has a wrong offset!");
static_assert(offsetof(BP_TresPlayerStateEventCamera_MikeBowling_C_ExecuteUbergraph_BP_TresPlayerStateEventCamera_MikeBowling, K2Node_Event_StateID) == 0x000252, "Member 'BP_TresPlayerStateEventCamera_MikeBowling_C_ExecuteUbergraph_BP_TresPlayerStateEventCamera_MikeBowling::K2Node_Event_StateID' has a wrong offset!");
static_assert(offsetof(BP_TresPlayerStateEventCamera_MikeBowling_C_ExecuteUbergraph_BP_TresPlayerStateEventCamera_MikeBowling, Temp_object_Variable) == 0x000258, "Member 'BP_TresPlayerStateEventCamera_MikeBowling_C_ExecuteUbergraph_BP_TresPlayerStateEventCamera_MikeBowling::Temp_object_Variable' has a wrong offset!");
static_assert(offsetof(BP_TresPlayerStateEventCamera_MikeBowling_C_ExecuteUbergraph_BP_TresPlayerStateEventCamera_MikeBowling, K2Node_SwitchEnum3_CmpSuccess) == 0x000268, "Member 'BP_TresPlayerStateEventCamera_MikeBowling_C_ExecuteUbergraph_BP_TresPlayerStateEventCamera_MikeBowling::K2Node_SwitchEnum3_CmpSuccess' has a wrong offset!");
static_assert(offsetof(BP_TresPlayerStateEventCamera_MikeBowling_C_ExecuteUbergraph_BP_TresPlayerStateEventCamera_MikeBowling, CallFunc_BP_TresLineTraceByChannel_OutHit) == 0x000270, "Member 'BP_TresPlayerStateEventCamera_MikeBowling_C_ExecuteUbergraph_BP_TresPlayerStateEventCamera_MikeBowling::CallFunc_BP_TresLineTraceByChannel_OutHit' has a wrong offset!");
static_assert(offsetof(BP_TresPlayerStateEventCamera_MikeBowling_C_ExecuteUbergraph_BP_TresPlayerStateEventCamera_MikeBowling, CallFunc_BP_TresLineTraceByChannel_ReturnValue) == 0x0002F8, "Member 'BP_TresPlayerStateEventCamera_MikeBowling_C_ExecuteUbergraph_BP_TresPlayerStateEventCamera_MikeBowling::CallFunc_BP_TresLineTraceByChannel_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_TresPlayerStateEventCamera_MikeBowling_C_ExecuteUbergraph_BP_TresPlayerStateEventCamera_MikeBowling, K2Node_MakeStruct_TresScreenBlurParams2) == 0x0002FC, "Member 'BP_TresPlayerStateEventCamera_MikeBowling_C_ExecuteUbergraph_BP_TresPlayerStateEventCamera_MikeBowling::K2Node_MakeStruct_TresScreenBlurParams2' has a wrong offset!");

// Function BP_TresPlayerStateEventCamera_MikeBowling.BP_TresPlayerStateEventCamera_MikeBowling_C.ReceivePlayerDtorState
// 0x8020800 (0x8020800 - 0x0000)
struct alignas(0x8020800) BP_TresPlayerStateEventCamera_MikeBowling_C_ReceivePlayerDtorState final
{
public:
	ETresStateID                                  StateID;                                           // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_TresPlayerStateEventCamera_MikeBowling_C_ReceivePlayerDtorState) == 0x8020800, "Wrong alignment on BP_TresPlayerStateEventCamera_MikeBowling_C_ReceivePlayerDtorState");
static_assert(sizeof(BP_TresPlayerStateEventCamera_MikeBowling_C_ReceivePlayerDtorState) == 0x8020800, "Wrong size on BP_TresPlayerStateEventCamera_MikeBowling_C_ReceivePlayerDtorState");
static_assert(offsetof(BP_TresPlayerStateEventCamera_MikeBowling_C_ReceivePlayerDtorState, StateID) == 0x000000, "Member 'BP_TresPlayerStateEventCamera_MikeBowling_C_ReceivePlayerDtorState::StateID' has a wrong offset!");

// Function BP_TresPlayerStateEventCamera_MikeBowling.BP_TresPlayerStateEventCamera_MikeBowling_C.ReceiveAnimNotifyStartBpEvent
// 0x8020800 (0x8020800 - 0x0000)
struct alignas(0x8020800) BP_TresPlayerStateEventCamera_MikeBowling_C_ReceiveAnimNotifyStartBpEvent final
{
public:
	class ATresCharPawnBase*                      SendActor;                                         // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   AnimSeqName;                                       // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ETresAnimNotifyBpEventID                      EventID;                                           // 0x0010(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_11[0x3];                                       // 0x0011(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Param;                                             // 0x0014(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_TresPlayerStateEventCamera_MikeBowling_C_ReceiveAnimNotifyStartBpEvent) == 0x8020800, "Wrong alignment on BP_TresPlayerStateEventCamera_MikeBowling_C_ReceiveAnimNotifyStartBpEvent");
static_assert(sizeof(BP_TresPlayerStateEventCamera_MikeBowling_C_ReceiveAnimNotifyStartBpEvent) == 0x8020800, "Wrong size on BP_TresPlayerStateEventCamera_MikeBowling_C_ReceiveAnimNotifyStartBpEvent");
static_assert(offsetof(BP_TresPlayerStateEventCamera_MikeBowling_C_ReceiveAnimNotifyStartBpEvent, SendActor) == 0x000000, "Member 'BP_TresPlayerStateEventCamera_MikeBowling_C_ReceiveAnimNotifyStartBpEvent::SendActor' has a wrong offset!");
static_assert(offsetof(BP_TresPlayerStateEventCamera_MikeBowling_C_ReceiveAnimNotifyStartBpEvent, AnimSeqName) == 0x000008, "Member 'BP_TresPlayerStateEventCamera_MikeBowling_C_ReceiveAnimNotifyStartBpEvent::AnimSeqName' has a wrong offset!");
static_assert(offsetof(BP_TresPlayerStateEventCamera_MikeBowling_C_ReceiveAnimNotifyStartBpEvent, EventID) == 0x000010, "Member 'BP_TresPlayerStateEventCamera_MikeBowling_C_ReceiveAnimNotifyStartBpEvent::EventID' has a wrong offset!");
static_assert(offsetof(BP_TresPlayerStateEventCamera_MikeBowling_C_ReceiveAnimNotifyStartBpEvent, Param) == 0x000014, "Member 'BP_TresPlayerStateEventCamera_MikeBowling_C_ReceiveAnimNotifyStartBpEvent::Param' has a wrong offset!");

// Function BP_TresPlayerStateEventCamera_MikeBowling.BP_TresPlayerStateEventCamera_MikeBowling_C.ReceivePlayerSpecificAction
// 0x800000 (0x800000 - 0x0000)
struct alignas(0x800000) BP_TresPlayerStateEventCamera_MikeBowling_C_ReceivePlayerSpecificAction final
{
public:
	ETresPlayerSpecificActionID                   ActionID;                                          // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1[0x3];                                        // 0x0001(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         SubID;                                             // 0x0004(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_TresPlayerStateEventCamera_MikeBowling_C_ReceivePlayerSpecificAction) == 0x800000, "Wrong alignment on BP_TresPlayerStateEventCamera_MikeBowling_C_ReceivePlayerSpecificAction");
static_assert(sizeof(BP_TresPlayerStateEventCamera_MikeBowling_C_ReceivePlayerSpecificAction) == 0x800000, "Wrong size on BP_TresPlayerStateEventCamera_MikeBowling_C_ReceivePlayerSpecificAction");
static_assert(offsetof(BP_TresPlayerStateEventCamera_MikeBowling_C_ReceivePlayerSpecificAction, ActionID) == 0x000000, "Member 'BP_TresPlayerStateEventCamera_MikeBowling_C_ReceivePlayerSpecificAction::ActionID' has a wrong offset!");
static_assert(offsetof(BP_TresPlayerStateEventCamera_MikeBowling_C_ReceivePlayerSpecificAction, SubID) == 0x000004, "Member 'BP_TresPlayerStateEventCamera_MikeBowling_C_ReceivePlayerSpecificAction::SubID' has a wrong offset!");

}

