#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_TresPlayerStateEventCam_ShootFlow

#include "Basic.hpp"

#include "BP_TresPlayerStateEventCam_ShootFlow_classes.hpp"
#include "BP_TresPlayerStateEventCam_ShootFlow_parameters.hpp"


namespace SDK
{

// Function BP_TresPlayerStateEventCam_ShootFlow.BP_TresPlayerStateEventCam_ShootFlow_C.ExecuteUbergraph_BP_TresPlayerStateEventCam_ShootFlow
// (HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_TresPlayerStateEventCam_ShootFlow_C::ExecuteUbergraph_BP_TresPlayerStateEventCam_ShootFlow(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_TresPlayerStateEventCam_ShootFlow_C", "ExecuteUbergraph_BP_TresPlayerStateEventCam_ShootFlow");

	Params::BP_TresPlayerStateEventCam_ShootFlow_C_ExecuteUbergraph_BP_TresPlayerStateEventCam_ShootFlow Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_TresPlayerStateEventCam_ShootFlow.BP_TresPlayerStateEventCam_ShootFlow_C.ReceivePlayerDtorState
// (Event, Public, BlueprintEvent)
// Parameters:
// ETresStateID                            StateID                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_TresPlayerStateEventCam_ShootFlow_C::ReceivePlayerDtorState(ETresStateID StateID)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_TresPlayerStateEventCam_ShootFlow_C", "ReceivePlayerDtorState");

	Params::BP_TresPlayerStateEventCam_ShootFlow_C_ReceivePlayerDtorState Parms{};

	Parms.StateID = StateID;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_TresPlayerStateEventCam_ShootFlow.BP_TresPlayerStateEventCam_ShootFlow_C.Tosshin
// (BlueprintCallable, BlueprintEvent)

void UBP_TresPlayerStateEventCam_ShootFlow_C::Tosshin()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_TresPlayerStateEventCam_ShootFlow_C", "Tosshin");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_TresPlayerStateEventCam_ShootFlow.BP_TresPlayerStateEventCam_ShootFlow_C.ReceivePlayerSpecificAction
// (Event, Public, BlueprintEvent)
// Parameters:
// ETresPlayerSpecificActionID             ActionID                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   SubID                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_TresPlayerStateEventCam_ShootFlow_C::ReceivePlayerSpecificAction(ETresPlayerSpecificActionID ActionID, int32 SubID)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_TresPlayerStateEventCam_ShootFlow_C", "ReceivePlayerSpecificAction");

	Params::BP_TresPlayerStateEventCam_ShootFlow_C_ReceivePlayerSpecificAction Parms{};

	Parms.ActionID = ActionID;
	Parms.SubID = SubID;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_TresPlayerStateEventCam_ShootFlow.BP_TresPlayerStateEventCam_ShootFlow_C.ReceiveAnimNotifyEndBpEvent
// (Event, Public, BlueprintEvent)
// Parameters:
// class ATresCharPawnBase*                SendActor                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class FName                             AnimSeqName                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// ETresAnimNotifyBpEventID                EventID                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   Param                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_TresPlayerStateEventCam_ShootFlow_C::ReceiveAnimNotifyEndBpEvent(class ATresCharPawnBase* SendActor, class FName AnimSeqName, ETresAnimNotifyBpEventID EventID, int32 Param)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_TresPlayerStateEventCam_ShootFlow_C", "ReceiveAnimNotifyEndBpEvent");

	Params::BP_TresPlayerStateEventCam_ShootFlow_C_ReceiveAnimNotifyEndBpEvent Parms{};

	Parms.SendActor = SendActor;
	Parms.AnimSeqName = AnimSeqName;
	Parms.EventID = EventID;
	Parms.Param = Param;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_TresPlayerStateEventCam_ShootFlow.BP_TresPlayerStateEventCam_ShootFlow_C.ReceiveAnimNotifyStartBpEvent
// (Event, Public, BlueprintEvent)
// Parameters:
// class ATresCharPawnBase*                SendActor                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class FName                             AnimSeqName                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// ETresAnimNotifyBpEventID                EventID                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   Param                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_TresPlayerStateEventCam_ShootFlow_C::ReceiveAnimNotifyStartBpEvent(class ATresCharPawnBase* SendActor, class FName AnimSeqName, ETresAnimNotifyBpEventID EventID, int32 Param)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_TresPlayerStateEventCam_ShootFlow_C", "ReceiveAnimNotifyStartBpEvent");

	Params::BP_TresPlayerStateEventCam_ShootFlow_C_ReceiveAnimNotifyStartBpEvent Parms{};

	Parms.SendActor = SendActor;
	Parms.AnimSeqName = AnimSeqName;
	Parms.EventID = EventID;
	Parms.Param = Param;

	UObject::ProcessEvent(Func, &Parms);
}

}

