#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: A_Lilith_PhasewalkDoor

#include "Basic.hpp"

#include "OakGame_classes.hpp"
#include "Engine_structs.hpp"
#include "GbxGameSystemCore_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass A_Lilith_PhasewalkDoor.A_Lilith_PhasewalkDoor_C
// 0x0008 (0x0220 - 0x0218)
class UA_Lilith_PhasewalkDoor_C final : public UOakAction_Anim
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0218(0x0008)(Transient, DuplicateTransient)

public:
	void OnBegin(class AActor* Actor);
	void OnEnd(EGbxActionEndState ActionEndState, class AActor* Actor);
	void PhaseOut();
	void PhaseIn();
	void ExecuteUbergraph_A_Lilith_PhasewalkDoor(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"A_Lilith_PhasewalkDoor_C">();
	}
	static class UA_Lilith_PhasewalkDoor_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UA_Lilith_PhasewalkDoor_C>();
	}
};
static_assert(alignof(UA_Lilith_PhasewalkDoor_C) == 0x000008, "Wrong alignment on UA_Lilith_PhasewalkDoor_C");
static_assert(sizeof(UA_Lilith_PhasewalkDoor_C) == 0x000220, "Wrong size on UA_Lilith_PhasewalkDoor_C");
static_assert(offsetof(UA_Lilith_PhasewalkDoor_C, UberGraphFrame) == 0x000218, "Member 'UA_Lilith_PhasewalkDoor_C::UberGraphFrame' has a wrong offset!");

}

