#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Ability_Artifact_StaticTouch

#include "Basic.hpp"

#include "Ability_Artifact_StaticTouch_classes.hpp"
#include "Ability_Artifact_StaticTouch_parameters.hpp"


namespace SDK
{

// Function Ability_Artifact_StaticTouch.Ability_Artifact_StaticTouch_C.ExecuteUbergraph_Ability_Artifact_StaticTouch
// (HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UAbility_Artifact_StaticTouch_C::ExecuteUbergraph_Ability_Artifact_StaticTouch(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Ability_Artifact_StaticTouch_C", "ExecuteUbergraph_Ability_Artifact_StaticTouch");

	Params::Ability_Artifact_StaticTouch_C_ExecuteUbergraph_Ability_Artifact_StaticTouch Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Ability_Artifact_StaticTouch.Ability_Artifact_StaticTouch_C.OnActivated
// (Event, Protected, BlueprintEvent)

void UAbility_Artifact_StaticTouch_C::OnActivated()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Ability_Artifact_StaticTouch_C", "OnActivated");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Ability_Artifact_StaticTouch.Ability_Artifact_StaticTouch_C.CausedDamage
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class AActor*                           DamageInstigator                                       (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   Damage                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UGbxDamageType*                   DamageType                                             (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UDamageSource*                    DamageSource                                           (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class AActor*                           DamagedActor                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FCausedDamageDetails             Details                                                (BlueprintVisible, BlueprintReadOnly, Parm, ContainsInstancedReference)

void UAbility_Artifact_StaticTouch_C::CausedDamage(class AActor* DamageInstigator, float Damage, const class UGbxDamageType* DamageType, const class UDamageSource* DamageSource, class AActor* DamagedActor, const struct FCausedDamageDetails& Details)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Ability_Artifact_StaticTouch_C", "CausedDamage");

	Params::Ability_Artifact_StaticTouch_C_CausedDamage Parms{};

	Parms.DamageInstigator = DamageInstigator;
	Parms.Damage = Damage;
	Parms.DamageType = DamageType;
	Parms.DamageSource = DamageSource;
	Parms.DamagedActor = DamagedActor;
	Parms.Details = std::move(Details);

	UObject::ProcessEvent(Func, &Parms);
}


// Function Ability_Artifact_StaticTouch.Ability_Artifact_StaticTouch_C.EndSlide
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FSlideEndedDetails               Details                                                (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, NoDestructor)

void UAbility_Artifact_StaticTouch_C::EndSlide(const struct FSlideEndedDetails& Details)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Ability_Artifact_StaticTouch_C", "EndSlide");

	Params::Ability_Artifact_StaticTouch_C_EndSlide Parms{};

	Parms.Details = std::move(Details);

	UObject::ProcessEvent(Func, &Parms);
}


// Function Ability_Artifact_StaticTouch.Ability_Artifact_StaticTouch_C.StartSlide
// (BlueprintCallable, BlueprintEvent)

void UAbility_Artifact_StaticTouch_C::StartSlide()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Ability_Artifact_StaticTouch_C", "StartSlide");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Ability_Artifact_StaticTouch.Ability_Artifact_StaticTouch_C.Ammo Return
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AOakCharacter*                    Character                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UAbility_Artifact_StaticTouch_C::Ammo_Return(class AOakCharacter* Character)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Ability_Artifact_StaticTouch_C", "Ammo Return");

	Params::Ability_Artifact_StaticTouch_C_Ammo_Return Parms{};

	Parms.Character = Character;

	UObject::ProcessEvent(Func, &Parms);
}

}

