#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Ability_Artifact_RoadWarrior1

#include "Basic.hpp"

#include "Ability_Artifact_RoadWarrior1_classes.hpp"
#include "Ability_Artifact_RoadWarrior1_parameters.hpp"


namespace SDK
{

// Function Ability_Artifact_RoadWarrior1.Ability_Artifact_RoadWarrior1_C.ExecuteUbergraph_Ability_Artifact_RoadWarrior1
// (HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UAbility_Artifact_RoadWarrior1_C::ExecuteUbergraph_Ability_Artifact_RoadWarrior1(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Ability_Artifact_RoadWarrior1_C", "ExecuteUbergraph_Ability_Artifact_RoadWarrior1");

	Params::Ability_Artifact_RoadWarrior1_C_ExecuteUbergraph_Ability_Artifact_RoadWarrior1 Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Ability_Artifact_RoadWarrior1.Ability_Artifact_RoadWarrior1_C.FireProjectile
// (BlueprintCallable, BlueprintEvent)

void UAbility_Artifact_RoadWarrior1_C::FireProjectile()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Ability_Artifact_RoadWarrior1_C", "FireProjectile");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Ability_Artifact_RoadWarrior1.Ability_Artifact_RoadWarrior1_C.OnActivated
// (Event, Protected, BlueprintEvent)

void UAbility_Artifact_RoadWarrior1_C::OnActivated()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Ability_Artifact_RoadWarrior1_C", "OnActivated");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Ability_Artifact_RoadWarrior1.Ability_Artifact_RoadWarrior1_C.OnDeactivated
// (Event, Protected, BlueprintEvent)

void UAbility_Artifact_RoadWarrior1_C::OnDeactivated()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Ability_Artifact_RoadWarrior1_C", "OnDeactivated");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Ability_Artifact_RoadWarrior1.Ability_Artifact_RoadWarrior1_C.StartSlide
// (BlueprintCallable, BlueprintEvent)

void UAbility_Artifact_RoadWarrior1_C::StartSlide()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Ability_Artifact_RoadWarrior1_C", "StartSlide");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Ability_Artifact_RoadWarrior1.Ability_Artifact_RoadWarrior1_C.StoppedSliding
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FSlideEndedDetails               Details                                                (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, NoDestructor)

void UAbility_Artifact_RoadWarrior1_C::StoppedSliding(const struct FSlideEndedDetails& Details)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Ability_Artifact_RoadWarrior1_C", "StoppedSliding");

	Params::Ability_Artifact_RoadWarrior1_C_StoppedSliding Parms{};

	Parms.Details = std::move(Details);

	UObject::ProcessEvent(Func, &Parms);
}

}

