#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Action_Nog_SurfStance_Enter

#include "Basic.hpp"

#include "Action_Nog_SurfStance_Enter_classes.hpp"
#include "Action_Nog_SurfStance_Enter_parameters.hpp"


namespace SDK
{

// Function Action_Nog_SurfStance_Enter.Action_Nog_SurfStance_Enter_C.ExecuteUbergraph_Action_Nog_SurfStance_Enter
// ()
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UAction_Nog_SurfStance_Enter_C::ExecuteUbergraph_Action_Nog_SurfStance_Enter(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Action_Nog_SurfStance_Enter_C", "ExecuteUbergraph_Action_Nog_SurfStance_Enter");

	Params::Action_Nog_SurfStance_Enter_C_ExecuteUbergraph_Action_Nog_SurfStance_Enter Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Action_Nog_SurfStance_Enter.Action_Nog_SurfStance_Enter_C.OnServerEnd
// (Event, Public, BlueprintEvent)
// Parameters:
// EGbxActionEndState                      ActionEndState                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class AActor*                           Actor                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UAction_Nog_SurfStance_Enter_C::OnServerEnd(EGbxActionEndState ActionEndState, class AActor* Actor)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Action_Nog_SurfStance_Enter_C", "OnServerEnd");

	Params::Action_Nog_SurfStance_Enter_C_OnServerEnd Parms{};

	Parms.ActionEndState = ActionEndState;
	Parms.Actor = Actor;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Action_Nog_SurfStance_Enter.Action_Nog_SurfStance_Enter_C.NotifyDroneBoardAssemble
// (BlueprintCallable, BlueprintEvent)

void UAction_Nog_SurfStance_Enter_C::NotifyDroneBoardAssemble()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Action_Nog_SurfStance_Enter_C", "NotifyDroneBoardAssemble");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Action_Nog_SurfStance_Enter.Action_Nog_SurfStance_Enter_C.NotifySurfStanceBegin
// (BlueprintCallable, BlueprintEvent)

void UAction_Nog_SurfStance_Enter_C::NotifySurfStanceBegin()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Action_Nog_SurfStance_Enter_C", "NotifySurfStanceBegin");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Action_Nog_SurfStance_Enter.Action_Nog_SurfStance_Enter_C.OnBegin
// (Event, Public, BlueprintEvent)
// Parameters:
// class AActor*                           Actor                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UAction_Nog_SurfStance_Enter_C::OnBegin(class AActor* Actor)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Action_Nog_SurfStance_Enter_C", "OnBegin");

	Params::Action_Nog_SurfStance_Enter_C_OnBegin Parms{};

	Parms.Actor = Actor;

	UObject::ProcessEvent(Func, &Parms);
}

}

