#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Action_Ava_Loop_LockPick

#include "Basic.hpp"

#include "GbxGameSystemCore_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Action_Ava_Loop_LockPick.Action_Ava_Loop_LockPick_C
// 0x0000 (0x03B8 - 0x03B8)
class UAction_Ava_Loop_LockPick_C final : public UGbxAction_Loop
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Action_Ava_Loop_LockPick_C">();
	}
	static class UAction_Ava_Loop_LockPick_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAction_Ava_Loop_LockPick_C>();
	}
};
static_assert(alignof(UAction_Ava_Loop_LockPick_C) == 0x000008, "Wrong alignment on UAction_Ava_Loop_LockPick_C");
static_assert(sizeof(UAction_Ava_Loop_LockPick_C) == 0x0003B8, "Wrong size on UAction_Ava_Loop_LockPick_C");

}

