#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AITree_VehicleDriver_Outrunner

#include "Basic.hpp"


namespace SDK::Params
{

// Function AITree_VehicleDriver_Outrunner.AITree_VehicleDriver_Outrunner_C.ExecuteUbergraph_AITree_VehicleDriver_Outrunner
// 0x0004 (0x0004 - 0x0000)
struct AITree_VehicleDriver_Outrunner_C_ExecuteUbergraph_AITree_VehicleDriver_Outrunner final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(AITree_VehicleDriver_Outrunner_C_ExecuteUbergraph_AITree_VehicleDriver_Outrunner) == 0x000004, "Wrong alignment on AITree_VehicleDriver_Outrunner_C_ExecuteUbergraph_AITree_VehicleDriver_Outrunner");
static_assert(sizeof(AITree_VehicleDriver_Outrunner_C_ExecuteUbergraph_AITree_VehicleDriver_Outrunner) == 0x000004, "Wrong size on AITree_VehicleDriver_Outrunner_C_ExecuteUbergraph_AITree_VehicleDriver_Outrunner");
static_assert(offsetof(AITree_VehicleDriver_Outrunner_C_ExecuteUbergraph_AITree_VehicleDriver_Outrunner, EntryPoint) == 0x000000, "Member 'AITree_VehicleDriver_Outrunner_C_ExecuteUbergraph_AITree_VehicleDriver_Outrunner::EntryPoint' has a wrong offset!");

}

