#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AITree_TrooperFlash_Malfunction

#include "Basic.hpp"

#include "AITree_TrooperFlash_Malfunction_classes.hpp"
#include "AITree_TrooperFlash_Malfunction_parameters.hpp"


namespace SDK
{

// Function AITree_TrooperFlash_Malfunction.AITree_TrooperFlash_Malfunction_C.ExecuteUbergraph_AITree_TrooperFlash_Malfunction
// ()
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UAITree_TrooperFlash_Malfunction_C::ExecuteUbergraph_AITree_TrooperFlash_Malfunction(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AITree_TrooperFlash_Malfunction_C", "ExecuteUbergraph_AITree_TrooperFlash_Malfunction");

	Params::AITree_TrooperFlash_Malfunction_C_ExecuteUbergraph_AITree_TrooperFlash_Malfunction Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

