#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ANav_HeavyBadass_ClimbUp

#include "Basic.hpp"

#include "ANav_Heavy_Parent_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass ANav_HeavyBadass_ClimbUp.ANav_HeavyBadass_ClimbUp_C
// 0x0000 (0x01B8 - 0x01B8)
class UANav_HeavyBadass_ClimbUp_C final : public UANav_Heavy_Parent_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"ANav_HeavyBadass_ClimbUp_C">();
	}
	static class UANav_HeavyBadass_ClimbUp_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UANav_HeavyBadass_ClimbUp_C>();
	}
};
static_assert(alignof(UANav_HeavyBadass_ClimbUp_C) == 0x000008, "Wrong alignment on UANav_HeavyBadass_ClimbUp_C");
static_assert(sizeof(UANav_HeavyBadass_ClimbUp_C) == 0x0001B8, "Wrong size on UANav_HeavyBadass_ClimbUp_C");

}

