#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ASpawn_LeapIn

#include "Basic.hpp"

#include "GbxSpawn_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass ASpawn_LeapIn.ASpawn_LeapIn_C
// 0x0000 (0x01C0 - 0x01C0)
class UASpawn_LeapIn_C final : public UGbxAction_SpawnAnim
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"ASpawn_LeapIn_C">();
	}
	static class UASpawn_LeapIn_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UASpawn_LeapIn_C>();
	}
};
static_assert(alignof(UASpawn_LeapIn_C) == 0x000008, "Wrong alignment on UASpawn_LeapIn_C");
static_assert(sizeof(UASpawn_LeapIn_C) == 0x0001C0, "Wrong size on UASpawn_LeapIn_C");

}

