#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_CS_ConsoleProxy

#include "Basic.hpp"

#include "BP_CS_ConsoleProxy_classes.hpp"
#include "BP_CS_ConsoleProxy_parameters.hpp"


namespace SDK
{

// Function BP_CS_ConsoleProxy.BP_CS_ConsoleProxy_C.ExecuteUbergraph_BP_CS_ConsoleProxy
// (HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_CS_ConsoleProxy_C::ExecuteUbergraph_BP_CS_ConsoleProxy(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CS_ConsoleProxy_C", "ExecuteUbergraph_BP_CS_ConsoleProxy");

	Params::BP_CS_ConsoleProxy_C_ExecuteUbergraph_BP_CS_ConsoleProxy Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_CS_ConsoleProxy.BP_CS_ConsoleProxy_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_CS_ConsoleProxy_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CS_ConsoleProxy_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_CS_ConsoleProxy.BP_CS_ConsoleProxy_C.OnOwningPlayerStartedInteraction
// (Event, Public, BlueprintEvent)

void ABP_CS_ConsoleProxy_C::OnOwningPlayerStartedInteraction()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CS_ConsoleProxy_C", "OnOwningPlayerStartedInteraction");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_CS_ConsoleProxy.BP_CS_ConsoleProxy_C.Stop Idle Dialog
// (BlueprintCallable, BlueprintEvent)

void ABP_CS_ConsoleProxy_C::Stop_Idle_Dialog()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CS_ConsoleProxy_C", "Stop Idle Dialog");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_CS_ConsoleProxy.BP_CS_ConsoleProxy_C.Play Idle Dialog
// (BlueprintCallable, BlueprintEvent)

void ABP_CS_ConsoleProxy_C::Play_Idle_Dialog()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CS_ConsoleProxy_C", "Play Idle Dialog");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_CS_ConsoleProxy.BP_CS_ConsoleProxy_C.OnEnterPuzzle
// (Event, Public, BlueprintEvent)

void ABP_CS_ConsoleProxy_C::OnEnterPuzzle()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CS_ConsoleProxy_C", "OnEnterPuzzle");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_CS_ConsoleProxy.BP_CS_ConsoleProxy_C.OnOwningPlayerStoppedInteraction
// (Event, Public, BlueprintEvent)

void ABP_CS_ConsoleProxy_C::OnOwningPlayerStoppedInteraction()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CS_ConsoleProxy_C", "OnOwningPlayerStoppedInteraction");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_CS_ConsoleProxy.BP_CS_ConsoleProxy_C.OnFirstPuzzleOfCurrentDifficulty
// (Event, Public, BlueprintEvent)

void ABP_CS_ConsoleProxy_C::OnFirstPuzzleOfCurrentDifficulty()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CS_ConsoleProxy_C", "OnFirstPuzzleOfCurrentDifficulty");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_CS_ConsoleProxy.BP_CS_ConsoleProxy_C.OnDifficultyLevelCompleted
// (Event, Public, BlueprintEvent)

void ABP_CS_ConsoleProxy_C::OnDifficultyLevelCompleted()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CS_ConsoleProxy_C", "OnDifficultyLevelCompleted");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_CS_ConsoleProxy.BP_CS_ConsoleProxy_C.OnUnderParScoreReached
// (Event, Public, BlueprintEvent)

void ABP_CS_ConsoleProxy_C::OnUnderParScoreReached()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CS_ConsoleProxy_C", "OnUnderParScoreReached");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_CS_ConsoleProxy.BP_CS_ConsoleProxy_C.OnSumbitPuzzleSolution
// (Event, Public, BlueprintEvent)
// Parameters:
// bool                                    bIsOptimal                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ABP_CS_ConsoleProxy_C::OnSumbitPuzzleSolution(bool bIsOptimal)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CS_ConsoleProxy_C", "OnSumbitPuzzleSolution");

	Params::BP_CS_ConsoleProxy_C_OnSumbitPuzzleSolution Parms{};

	Parms.bIsOptimal = bIsOptimal;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_CS_ConsoleProxy.BP_CS_ConsoleProxy_C.OnOptimalScoreReached
// (Event, Public, BlueprintEvent)

void ABP_CS_ConsoleProxy_C::OnOptimalScoreReached()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CS_ConsoleProxy_C", "OnOptimalScoreReached");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_CS_ConsoleProxy.BP_CS_ConsoleProxy_C.OnParScoreReached
// (Event, Public, BlueprintEvent)

void ABP_CS_ConsoleProxy_C::OnParScoreReached()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CS_ConsoleProxy_C", "OnParScoreReached");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_CS_ConsoleProxy.BP_CS_ConsoleProxy_C.OUT__UpdateFunc
// (BlueprintEvent)

void ABP_CS_ConsoleProxy_C::OUT__UpdateFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CS_ConsoleProxy_C", "OUT__UpdateFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_CS_ConsoleProxy.BP_CS_ConsoleProxy_C.OUT__FinishedFunc
// (BlueprintEvent)

void ABP_CS_ConsoleProxy_C::OUT__FinishedFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CS_ConsoleProxy_C", "OUT__FinishedFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_CS_ConsoleProxy.BP_CS_ConsoleProxy_C.OnOptimal__UpdateFunc
// (BlueprintEvent)

void ABP_CS_ConsoleProxy_C::OnOptimal__UpdateFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CS_ConsoleProxy_C", "OnOptimal__UpdateFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_CS_ConsoleProxy.BP_CS_ConsoleProxy_C.OnOptimal__FinishedFunc
// (BlueprintEvent)

void ABP_CS_ConsoleProxy_C::OnOptimal__FinishedFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CS_ConsoleProxy_C", "OnOptimal__FinishedFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_CS_ConsoleProxy.BP_CS_ConsoleProxy_C.OnPar__UpdateFunc
// (BlueprintEvent)

void ABP_CS_ConsoleProxy_C::OnPar__UpdateFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CS_ConsoleProxy_C", "OnPar__UpdateFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_CS_ConsoleProxy.BP_CS_ConsoleProxy_C.OnPar__FinishedFunc
// (BlueprintEvent)

void ABP_CS_ConsoleProxy_C::OnPar__FinishedFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CS_ConsoleProxy_C", "OnPar__FinishedFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_CS_ConsoleProxy.BP_CS_ConsoleProxy_C.SubParReached__UpdateFunc
// (BlueprintEvent)

void ABP_CS_ConsoleProxy_C::SubParReached__UpdateFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CS_ConsoleProxy_C", "SubParReached__UpdateFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_CS_ConsoleProxy.BP_CS_ConsoleProxy_C.SubParReached__FinishedFunc
// (BlueprintEvent)

void ABP_CS_ConsoleProxy_C::SubParReached__FinishedFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CS_ConsoleProxy_C", "SubParReached__FinishedFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_CS_ConsoleProxy.BP_CS_ConsoleProxy_C.IN__UpdateFunc
// (BlueprintEvent)

void ABP_CS_ConsoleProxy_C::IN__UpdateFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CS_ConsoleProxy_C", "IN__UpdateFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_CS_ConsoleProxy.BP_CS_ConsoleProxy_C.IN__FinishedFunc
// (BlueprintEvent)

void ABP_CS_ConsoleProxy_C::IN__FinishedFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CS_ConsoleProxy_C", "IN__FinishedFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_CS_ConsoleProxy.BP_CS_ConsoleProxy_C.UserConstructionScript
// (Event, Public, BlueprintCallable, BlueprintEvent)

void ABP_CS_ConsoleProxy_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CS_ConsoleProxy_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_CS_ConsoleProxy.BP_CS_ConsoleProxy_C.PlayDialog
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             OpponentName                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// EDialogEventEnum                        DialogType_0                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FDialogConversation              Conversation                                           (Parm, OutParm, NoDestructor, HasGetValueTypeHash)

void ABP_CS_ConsoleProxy_C::PlayDialog(class FName OpponentName, EDialogEventEnum DialogType_0, struct FDialogConversation* Conversation)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CS_ConsoleProxy_C", "PlayDialog");

	Params::BP_CS_ConsoleProxy_C_PlayDialog Parms{};

	Parms.OpponentName = OpponentName;
	Parms.DialogType_0 = DialogType_0;

	UObject::ProcessEvent(Func, &Parms);

	if (Conversation != nullptr)
		*Conversation = std::move(Parms.Conversation);
}

}

