#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_GM_Payload_WidowMaker

#include "Basic.hpp"

#include "GbxWeapon_structs.hpp"
#include "Engine_structs.hpp"
#include "OakGame_structs.hpp"
#include "GbxGameSystemCore_structs.hpp"
#include "CoreUObject_structs.hpp"


namespace SDK::Params
{

// Function BP_GM_Payload_WidowMaker.BP_GM_Payload_WidowMaker_C.K2_GrenadeImpact
// 0x0240 (0x0240 - 0x0000)
struct BP_GM_Payload_WidowMaker_C_K2_GrenadeImpact final
{
public:
	class AGrenade*                               Grenade;                                           // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AGrenadeMod*                            GrenadeMod;                                        // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FHitResult                             HitResult;                                         // 0x0010(0x0090)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, IsPlainOldData, NoDestructor, ContainsInstancedReference)
	struct FPayloadInstanceData                   InstanceData;                                      // 0x00A0(0x0030)(BlueprintVisible, Parm, OutParm, ReferenceParm, NoDestructor)
	bool                                          CallFunc_GrenadeUsesPayload_ReturnValue;           // 0x00D0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BreakHitResult_bBlockingHit;              // 0x00D1(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BreakHitResult_bInitialOverlap;           // 0x00D2(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_D3[0x1];                                       // 0x00D3(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_BreakHitResult_Time;                      // 0x00D4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakHitResult_Distance;                  // 0x00D8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_Location;                  // 0x00DC(0x000C)(IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_ImpactPoint;               // 0x00E8(0x000C)(IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_Normal;                    // 0x00F4(0x000C)(IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_ImpactNormal;              // 0x0100(0x000C)(IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_10C[0x4];                                      // 0x010C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UPhysicalMaterial*                      CallFunc_BreakHitResult_PhysMat;                   // 0x0110(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 CallFunc_BreakHitResult_HitActor;                  // 0x0118(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UPrimitiveComponent*                    CallFunc_BreakHitResult_HitComponent;              // 0x0120(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   CallFunc_BreakHitResult_HitBoneName;               // 0x0128(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_BreakHitResult_HitItem;                   // 0x0130(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_BreakHitResult_FaceIndex;                 // 0x0134(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_TraceStart;                // 0x0138(0x000C)(IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_TraceEnd;                  // 0x0144(0x000C)(IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FGrenadeChildGenerationData            CallFunc_GetChildOffset_ReturnValue;               // 0x0150(0x0028)(NoDestructor)
	struct FVector                                CallFunc_Multiply_VectorFloat_ReturnValue;         // 0x0178(0x000C)(IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_Add_VectorVector_ReturnValue;             // 0x0184(0x000C)(IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x0190(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_191[0x3];                                      // 0x0191(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FRotator                               CallFunc_MakeRotFromZ_ReturnValue;                 // 0x0194(0x000C)(IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BooleanAND_ReturnValue;                   // 0x01A0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1A1[0x7];                                      // 0x01A1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FHitResult                             CallFunc_K2_SetActorLocation_SweepHitResult;       // 0x01A8(0x0090)(IsPlainOldData, NoDestructor, ContainsInstancedReference)
	bool                                          CallFunc_K2_SetActorLocation_ReturnValue;          // 0x0238(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_K2_SetActorRotation_ReturnValue;          // 0x0239(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(BP_GM_Payload_WidowMaker_C_K2_GrenadeImpact) == 0x000008, "Wrong alignment on BP_GM_Payload_WidowMaker_C_K2_GrenadeImpact");
static_assert(sizeof(BP_GM_Payload_WidowMaker_C_K2_GrenadeImpact) == 0x000240, "Wrong size on BP_GM_Payload_WidowMaker_C_K2_GrenadeImpact");
static_assert(offsetof(BP_GM_Payload_WidowMaker_C_K2_GrenadeImpact, Grenade) == 0x000000, "Member 'BP_GM_Payload_WidowMaker_C_K2_GrenadeImpact::Grenade' has a wrong offset!");
static_assert(offsetof(BP_GM_Payload_WidowMaker_C_K2_GrenadeImpact, GrenadeMod) == 0x000008, "Member 'BP_GM_Payload_WidowMaker_C_K2_GrenadeImpact::GrenadeMod' has a wrong offset!");
static_assert(offsetof(BP_GM_Payload_WidowMaker_C_K2_GrenadeImpact, HitResult) == 0x000010, "Member 'BP_GM_Payload_WidowMaker_C_K2_GrenadeImpact::HitResult' has a wrong offset!");
static_assert(offsetof(BP_GM_Payload_WidowMaker_C_K2_GrenadeImpact, InstanceData) == 0x0000A0, "Member 'BP_GM_Payload_WidowMaker_C_K2_GrenadeImpact::InstanceData' has a wrong offset!");
static_assert(offsetof(BP_GM_Payload_WidowMaker_C_K2_GrenadeImpact, CallFunc_GrenadeUsesPayload_ReturnValue) == 0x0000D0, "Member 'BP_GM_Payload_WidowMaker_C_K2_GrenadeImpact::CallFunc_GrenadeUsesPayload_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_GM_Payload_WidowMaker_C_K2_GrenadeImpact, CallFunc_BreakHitResult_bBlockingHit) == 0x0000D1, "Member 'BP_GM_Payload_WidowMaker_C_K2_GrenadeImpact::CallFunc_BreakHitResult_bBlockingHit' has a wrong offset!");
static_assert(offsetof(BP_GM_Payload_WidowMaker_C_K2_GrenadeImpact, CallFunc_BreakHitResult_bInitialOverlap) == 0x0000D2, "Member 'BP_GM_Payload_WidowMaker_C_K2_GrenadeImpact::CallFunc_BreakHitResult_bInitialOverlap' has a wrong offset!");
static_assert(offsetof(BP_GM_Payload_WidowMaker_C_K2_GrenadeImpact, CallFunc_BreakHitResult_Time) == 0x0000D4, "Member 'BP_GM_Payload_WidowMaker_C_K2_GrenadeImpact::CallFunc_BreakHitResult_Time' has a wrong offset!");
static_assert(offsetof(BP_GM_Payload_WidowMaker_C_K2_GrenadeImpact, CallFunc_BreakHitResult_Distance) == 0x0000D8, "Member 'BP_GM_Payload_WidowMaker_C_K2_GrenadeImpact::CallFunc_BreakHitResult_Distance' has a wrong offset!");
static_assert(offsetof(BP_GM_Payload_WidowMaker_C_K2_GrenadeImpact, CallFunc_BreakHitResult_Location) == 0x0000DC, "Member 'BP_GM_Payload_WidowMaker_C_K2_GrenadeImpact::CallFunc_BreakHitResult_Location' has a wrong offset!");
static_assert(offsetof(BP_GM_Payload_WidowMaker_C_K2_GrenadeImpact, CallFunc_BreakHitResult_ImpactPoint) == 0x0000E8, "Member 'BP_GM_Payload_WidowMaker_C_K2_GrenadeImpact::CallFunc_BreakHitResult_ImpactPoint' has a wrong offset!");
static_assert(offsetof(BP_GM_Payload_WidowMaker_C_K2_GrenadeImpact, CallFunc_BreakHitResult_Normal) == 0x0000F4, "Member 'BP_GM_Payload_WidowMaker_C_K2_GrenadeImpact::CallFunc_BreakHitResult_Normal' has a wrong offset!");
static_assert(offsetof(BP_GM_Payload_WidowMaker_C_K2_GrenadeImpact, CallFunc_BreakHitResult_ImpactNormal) == 0x000100, "Member 'BP_GM_Payload_WidowMaker_C_K2_GrenadeImpact::CallFunc_BreakHitResult_ImpactNormal' has a wrong offset!");
static_assert(offsetof(BP_GM_Payload_WidowMaker_C_K2_GrenadeImpact, CallFunc_BreakHitResult_PhysMat) == 0x000110, "Member 'BP_GM_Payload_WidowMaker_C_K2_GrenadeImpact::CallFunc_BreakHitResult_PhysMat' has a wrong offset!");
static_assert(offsetof(BP_GM_Payload_WidowMaker_C_K2_GrenadeImpact, CallFunc_BreakHitResult_HitActor) == 0x000118, "Member 'BP_GM_Payload_WidowMaker_C_K2_GrenadeImpact::CallFunc_BreakHitResult_HitActor' has a wrong offset!");
static_assert(offsetof(BP_GM_Payload_WidowMaker_C_K2_GrenadeImpact, CallFunc_BreakHitResult_HitComponent) == 0x000120, "Member 'BP_GM_Payload_WidowMaker_C_K2_GrenadeImpact::CallFunc_BreakHitResult_HitComponent' has a wrong offset!");
static_assert(offsetof(BP_GM_Payload_WidowMaker_C_K2_GrenadeImpact, CallFunc_BreakHitResult_HitBoneName) == 0x000128, "Member 'BP_GM_Payload_WidowMaker_C_K2_GrenadeImpact::CallFunc_BreakHitResult_HitBoneName' has a wrong offset!");
static_assert(offsetof(BP_GM_Payload_WidowMaker_C_K2_GrenadeImpact, CallFunc_BreakHitResult_HitItem) == 0x000130, "Member 'BP_GM_Payload_WidowMaker_C_K2_GrenadeImpact::CallFunc_BreakHitResult_HitItem' has a wrong offset!");
static_assert(offsetof(BP_GM_Payload_WidowMaker_C_K2_GrenadeImpact, CallFunc_BreakHitResult_FaceIndex) == 0x000134, "Member 'BP_GM_Payload_WidowMaker_C_K2_GrenadeImpact::CallFunc_BreakHitResult_FaceIndex' has a wrong offset!");
static_assert(offsetof(BP_GM_Payload_WidowMaker_C_K2_GrenadeImpact, CallFunc_BreakHitResult_TraceStart) == 0x000138, "Member 'BP_GM_Payload_WidowMaker_C_K2_GrenadeImpact::CallFunc_BreakHitResult_TraceStart' has a wrong offset!");
static_assert(offsetof(BP_GM_Payload_WidowMaker_C_K2_GrenadeImpact, CallFunc_BreakHitResult_TraceEnd) == 0x000144, "Member 'BP_GM_Payload_WidowMaker_C_K2_GrenadeImpact::CallFunc_BreakHitResult_TraceEnd' has a wrong offset!");
static_assert(offsetof(BP_GM_Payload_WidowMaker_C_K2_GrenadeImpact, CallFunc_GetChildOffset_ReturnValue) == 0x000150, "Member 'BP_GM_Payload_WidowMaker_C_K2_GrenadeImpact::CallFunc_GetChildOffset_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_GM_Payload_WidowMaker_C_K2_GrenadeImpact, CallFunc_Multiply_VectorFloat_ReturnValue) == 0x000178, "Member 'BP_GM_Payload_WidowMaker_C_K2_GrenadeImpact::CallFunc_Multiply_VectorFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_GM_Payload_WidowMaker_C_K2_GrenadeImpact, CallFunc_Add_VectorVector_ReturnValue) == 0x000184, "Member 'BP_GM_Payload_WidowMaker_C_K2_GrenadeImpact::CallFunc_Add_VectorVector_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_GM_Payload_WidowMaker_C_K2_GrenadeImpact, CallFunc_Less_IntInt_ReturnValue) == 0x000190, "Member 'BP_GM_Payload_WidowMaker_C_K2_GrenadeImpact::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_GM_Payload_WidowMaker_C_K2_GrenadeImpact, CallFunc_MakeRotFromZ_ReturnValue) == 0x000194, "Member 'BP_GM_Payload_WidowMaker_C_K2_GrenadeImpact::CallFunc_MakeRotFromZ_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_GM_Payload_WidowMaker_C_K2_GrenadeImpact, CallFunc_BooleanAND_ReturnValue) == 0x0001A0, "Member 'BP_GM_Payload_WidowMaker_C_K2_GrenadeImpact::CallFunc_BooleanAND_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_GM_Payload_WidowMaker_C_K2_GrenadeImpact, CallFunc_K2_SetActorLocation_SweepHitResult) == 0x0001A8, "Member 'BP_GM_Payload_WidowMaker_C_K2_GrenadeImpact::CallFunc_K2_SetActorLocation_SweepHitResult' has a wrong offset!");
static_assert(offsetof(BP_GM_Payload_WidowMaker_C_K2_GrenadeImpact, CallFunc_K2_SetActorLocation_ReturnValue) == 0x000238, "Member 'BP_GM_Payload_WidowMaker_C_K2_GrenadeImpact::CallFunc_K2_SetActorLocation_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_GM_Payload_WidowMaker_C_K2_GrenadeImpact, CallFunc_K2_SetActorRotation_ReturnValue) == 0x000239, "Member 'BP_GM_Payload_WidowMaker_C_K2_GrenadeImpact::CallFunc_K2_SetActorRotation_ReturnValue' has a wrong offset!");

// Function BP_GM_Payload_WidowMaker.BP_GM_Payload_WidowMaker_C.K2_GrenadeExplode
// 0x00A0 (0x00A0 - 0x0000)
struct BP_GM_Payload_WidowMaker_C_K2_GrenadeExplode final
{
public:
	class AGrenade*                               Grenade;                                           // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AGrenadeMod*                            GrenadeMod;                                        // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FPayloadInstanceData                   InstanceData;                                      // 0x0010(0x0030)(BlueprintVisible, Parm, OutParm, ReferenceParm, NoDestructor)
	bool                                          CallFunc_GrenadeUsesPayload_ReturnValue;           // 0x0040(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_41[0x3];                                       // 0x0041(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGrenadeChildGenerationData            CallFunc_GetChildOffset_ReturnValue;               // 0x0044(0x0028)(NoDestructor)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x006C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BooleanAND_ReturnValue;                   // 0x006D(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_6E[0x2];                                       // 0x006E(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	class UParticleSystemComponent*               CallFunc_SpawnEmitterAttached_ReturnValue;         // 0x0070(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FRotator                               CallFunc_K2_GetActorRotation_ReturnValue;          // 0x0078(0x000C)(IsPlainOldData, NoDestructor)
	struct FVector                                CallFunc_GetUpVector_ReturnValue;                  // 0x0084(0x000C)(IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_Multiply_VectorFloat_ReturnValue;         // 0x0090(0x000C)(IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_GM_Payload_WidowMaker_C_K2_GrenadeExplode) == 0x000008, "Wrong alignment on BP_GM_Payload_WidowMaker_C_K2_GrenadeExplode");
static_assert(sizeof(BP_GM_Payload_WidowMaker_C_K2_GrenadeExplode) == 0x0000A0, "Wrong size on BP_GM_Payload_WidowMaker_C_K2_GrenadeExplode");
static_assert(offsetof(BP_GM_Payload_WidowMaker_C_K2_GrenadeExplode, Grenade) == 0x000000, "Member 'BP_GM_Payload_WidowMaker_C_K2_GrenadeExplode::Grenade' has a wrong offset!");
static_assert(offsetof(BP_GM_Payload_WidowMaker_C_K2_GrenadeExplode, GrenadeMod) == 0x000008, "Member 'BP_GM_Payload_WidowMaker_C_K2_GrenadeExplode::GrenadeMod' has a wrong offset!");
static_assert(offsetof(BP_GM_Payload_WidowMaker_C_K2_GrenadeExplode, InstanceData) == 0x000010, "Member 'BP_GM_Payload_WidowMaker_C_K2_GrenadeExplode::InstanceData' has a wrong offset!");
static_assert(offsetof(BP_GM_Payload_WidowMaker_C_K2_GrenadeExplode, CallFunc_GrenadeUsesPayload_ReturnValue) == 0x000040, "Member 'BP_GM_Payload_WidowMaker_C_K2_GrenadeExplode::CallFunc_GrenadeUsesPayload_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_GM_Payload_WidowMaker_C_K2_GrenadeExplode, CallFunc_GetChildOffset_ReturnValue) == 0x000044, "Member 'BP_GM_Payload_WidowMaker_C_K2_GrenadeExplode::CallFunc_GetChildOffset_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_GM_Payload_WidowMaker_C_K2_GrenadeExplode, CallFunc_Less_IntInt_ReturnValue) == 0x00006C, "Member 'BP_GM_Payload_WidowMaker_C_K2_GrenadeExplode::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_GM_Payload_WidowMaker_C_K2_GrenadeExplode, CallFunc_BooleanAND_ReturnValue) == 0x00006D, "Member 'BP_GM_Payload_WidowMaker_C_K2_GrenadeExplode::CallFunc_BooleanAND_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_GM_Payload_WidowMaker_C_K2_GrenadeExplode, CallFunc_SpawnEmitterAttached_ReturnValue) == 0x000070, "Member 'BP_GM_Payload_WidowMaker_C_K2_GrenadeExplode::CallFunc_SpawnEmitterAttached_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_GM_Payload_WidowMaker_C_K2_GrenadeExplode, CallFunc_K2_GetActorRotation_ReturnValue) == 0x000078, "Member 'BP_GM_Payload_WidowMaker_C_K2_GrenadeExplode::CallFunc_K2_GetActorRotation_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_GM_Payload_WidowMaker_C_K2_GrenadeExplode, CallFunc_GetUpVector_ReturnValue) == 0x000084, "Member 'BP_GM_Payload_WidowMaker_C_K2_GrenadeExplode::CallFunc_GetUpVector_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_GM_Payload_WidowMaker_C_K2_GrenadeExplode, CallFunc_Multiply_VectorFloat_ReturnValue) == 0x000090, "Member 'BP_GM_Payload_WidowMaker_C_K2_GrenadeExplode::CallFunc_Multiply_VectorFloat_ReturnValue' has a wrong offset!");

// Function BP_GM_Payload_WidowMaker.BP_GM_Payload_WidowMaker_C.K2_NativeDelayCallback
// 0x02E0 (0x02E0 - 0x0000)
struct BP_GM_Payload_WidowMaker_C_K2_NativeDelayCallback final
{
public:
	class AGrenade*                               Grenade;                                           // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AGrenadeMod*                            GrenadeMod;                                        // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FPayloadInstanceData                   InstanceData;                                      // 0x0010(0x0030)(BlueprintVisible, Parm, OutParm, ReferenceParm, NoDestructor)
	class FName                                   DelayName;                                         // 0x0040(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 Target;                                            // 0x0048(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x0050(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_SwitchName_CmpSuccess;                      // 0x0054(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_55[0x3];                                       // 0x0055(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0058(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable;                     // 0x005C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<class AActor*>                         CallFunc_GetAttachedActors_OutActors;              // 0x0060(0x0010)(ZeroConstructor, ReferenceParm)
	class AActor*                                 CallFunc_Array_Get_Item;                           // 0x0070(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_GetVelocity_ReturnValue;                  // 0x0078(0x000C)(IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_NegateVector_ReturnValue;                 // 0x0084(0x000C)(IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_K2_GetActorLocation_ReturnValue;          // 0x0090(0x000C)(IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_9C[0x4];                                       // 0x009C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<struct FTransform>                     CallFunc_GeneratePointsOnCone_ReturnValue;         // 0x00A0(0x0010)(ZeroConstructor, ReferenceParm)
	class UGrenadeHomingComponent*                CallFunc_GetHomingComponent_ReturnValue;           // 0x00B0(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_B8[0x8];                                       // 0x00B8(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTransform                             CallFunc_Array_Get_Item1;                          // 0x00C0(0x0030)(IsPlainOldData, NoDestructor)
	struct FVector                                CallFunc_BreakTransform_Location;                  // 0x00F0(0x000C)(IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FRotator                               CallFunc_BreakTransform_Rotation;                  // 0x00FC(0x000C)(IsPlainOldData, NoDestructor)
	struct FVector                                CallFunc_BreakTransform_Scale;                     // 0x0108(0x000C)(IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0114(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_115[0x3];                                      // 0x0115(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                CallFunc_GetForwardVector_ReturnValue;             // 0x0118(0x000C)(IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_Multiply_VectorFloat_ReturnValue;         // 0x0124(0x000C)(IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_Add_VectorVector_ReturnValue;             // 0x0130(0x000C)(IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x013C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x0140(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_141[0x7];                                      // 0x0141(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FForceSelection                        CallFunc_Conv_FloatToForceSelection_ReturnValue;   // 0x0148(0x0020)(NoDestructor)
	class AActor*                                 CallFunc_GetOwner_ReturnValue;                     // 0x0168(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_K2_GetActorLocation_ReturnValue1;         // 0x0170(0x000C)(IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakVector_X;                            // 0x017C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakVector_Y;                            // 0x0180(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakVector_Z;                            // 0x0184(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Add_FloatFloat_ReturnValue;               // 0x0188(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_MakeVector_ReturnValue;                   // 0x018C(0x000C)(IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FLightProjectileInitializationData     K2Node_MakeStruct_LightProjectileInitializationData; // 0x0198(0x0140)(ContainsInstancedReference)
};
static_assert(alignof(BP_GM_Payload_WidowMaker_C_K2_NativeDelayCallback) == 0x000010, "Wrong alignment on BP_GM_Payload_WidowMaker_C_K2_NativeDelayCallback");
static_assert(sizeof(BP_GM_Payload_WidowMaker_C_K2_NativeDelayCallback) == 0x0002E0, "Wrong size on BP_GM_Payload_WidowMaker_C_K2_NativeDelayCallback");
static_assert(offsetof(BP_GM_Payload_WidowMaker_C_K2_NativeDelayCallback, Grenade) == 0x000000, "Member 'BP_GM_Payload_WidowMaker_C_K2_NativeDelayCallback::Grenade' has a wrong offset!");
static_assert(offsetof(BP_GM_Payload_WidowMaker_C_K2_NativeDelayCallback, GrenadeMod) == 0x000008, "Member 'BP_GM_Payload_WidowMaker_C_K2_NativeDelayCallback::GrenadeMod' has a wrong offset!");
static_assert(offsetof(BP_GM_Payload_WidowMaker_C_K2_NativeDelayCallback, InstanceData) == 0x000010, "Member 'BP_GM_Payload_WidowMaker_C_K2_NativeDelayCallback::InstanceData' has a wrong offset!");
static_assert(offsetof(BP_GM_Payload_WidowMaker_C_K2_NativeDelayCallback, DelayName) == 0x000040, "Member 'BP_GM_Payload_WidowMaker_C_K2_NativeDelayCallback::DelayName' has a wrong offset!");
static_assert(offsetof(BP_GM_Payload_WidowMaker_C_K2_NativeDelayCallback, Target) == 0x000048, "Member 'BP_GM_Payload_WidowMaker_C_K2_NativeDelayCallback::Target' has a wrong offset!");
static_assert(offsetof(BP_GM_Payload_WidowMaker_C_K2_NativeDelayCallback, Temp_int_Loop_Counter_Variable) == 0x000050, "Member 'BP_GM_Payload_WidowMaker_C_K2_NativeDelayCallback::Temp_int_Loop_Counter_Variable' has a wrong offset!");
static_assert(offsetof(BP_GM_Payload_WidowMaker_C_K2_NativeDelayCallback, K2Node_SwitchName_CmpSuccess) == 0x000054, "Member 'BP_GM_Payload_WidowMaker_C_K2_NativeDelayCallback::K2Node_SwitchName_CmpSuccess' has a wrong offset!");
static_assert(offsetof(BP_GM_Payload_WidowMaker_C_K2_NativeDelayCallback, CallFunc_Add_IntInt_ReturnValue) == 0x000058, "Member 'BP_GM_Payload_WidowMaker_C_K2_NativeDelayCallback::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_GM_Payload_WidowMaker_C_K2_NativeDelayCallback, Temp_int_Array_Index_Variable) == 0x00005C, "Member 'BP_GM_Payload_WidowMaker_C_K2_NativeDelayCallback::Temp_int_Array_Index_Variable' has a wrong offset!");
static_assert(offsetof(BP_GM_Payload_WidowMaker_C_K2_NativeDelayCallback, CallFunc_GetAttachedActors_OutActors) == 0x000060, "Member 'BP_GM_Payload_WidowMaker_C_K2_NativeDelayCallback::CallFunc_GetAttachedActors_OutActors' has a wrong offset!");
static_assert(offsetof(BP_GM_Payload_WidowMaker_C_K2_NativeDelayCallback, CallFunc_Array_Get_Item) == 0x000070, "Member 'BP_GM_Payload_WidowMaker_C_K2_NativeDelayCallback::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(BP_GM_Payload_WidowMaker_C_K2_NativeDelayCallback, CallFunc_GetVelocity_ReturnValue) == 0x000078, "Member 'BP_GM_Payload_WidowMaker_C_K2_NativeDelayCallback::CallFunc_GetVelocity_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_GM_Payload_WidowMaker_C_K2_NativeDelayCallback, CallFunc_NegateVector_ReturnValue) == 0x000084, "Member 'BP_GM_Payload_WidowMaker_C_K2_NativeDelayCallback::CallFunc_NegateVector_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_GM_Payload_WidowMaker_C_K2_NativeDelayCallback, CallFunc_K2_GetActorLocation_ReturnValue) == 0x000090, "Member 'BP_GM_Payload_WidowMaker_C_K2_NativeDelayCallback::CallFunc_K2_GetActorLocation_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_GM_Payload_WidowMaker_C_K2_NativeDelayCallback, CallFunc_GeneratePointsOnCone_ReturnValue) == 0x0000A0, "Member 'BP_GM_Payload_WidowMaker_C_K2_NativeDelayCallback::CallFunc_GeneratePointsOnCone_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_GM_Payload_WidowMaker_C_K2_NativeDelayCallback, CallFunc_GetHomingComponent_ReturnValue) == 0x0000B0, "Member 'BP_GM_Payload_WidowMaker_C_K2_NativeDelayCallback::CallFunc_GetHomingComponent_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_GM_Payload_WidowMaker_C_K2_NativeDelayCallback, CallFunc_Array_Get_Item1) == 0x0000C0, "Member 'BP_GM_Payload_WidowMaker_C_K2_NativeDelayCallback::CallFunc_Array_Get_Item1' has a wrong offset!");
static_assert(offsetof(BP_GM_Payload_WidowMaker_C_K2_NativeDelayCallback, CallFunc_BreakTransform_Location) == 0x0000F0, "Member 'BP_GM_Payload_WidowMaker_C_K2_NativeDelayCallback::CallFunc_BreakTransform_Location' has a wrong offset!");
static_assert(offsetof(BP_GM_Payload_WidowMaker_C_K2_NativeDelayCallback, CallFunc_BreakTransform_Rotation) == 0x0000FC, "Member 'BP_GM_Payload_WidowMaker_C_K2_NativeDelayCallback::CallFunc_BreakTransform_Rotation' has a wrong offset!");
static_assert(offsetof(BP_GM_Payload_WidowMaker_C_K2_NativeDelayCallback, CallFunc_BreakTransform_Scale) == 0x000108, "Member 'BP_GM_Payload_WidowMaker_C_K2_NativeDelayCallback::CallFunc_BreakTransform_Scale' has a wrong offset!");
static_assert(offsetof(BP_GM_Payload_WidowMaker_C_K2_NativeDelayCallback, CallFunc_IsValid_ReturnValue) == 0x000114, "Member 'BP_GM_Payload_WidowMaker_C_K2_NativeDelayCallback::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_GM_Payload_WidowMaker_C_K2_NativeDelayCallback, CallFunc_GetForwardVector_ReturnValue) == 0x000118, "Member 'BP_GM_Payload_WidowMaker_C_K2_NativeDelayCallback::CallFunc_GetForwardVector_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_GM_Payload_WidowMaker_C_K2_NativeDelayCallback, CallFunc_Multiply_VectorFloat_ReturnValue) == 0x000124, "Member 'BP_GM_Payload_WidowMaker_C_K2_NativeDelayCallback::CallFunc_Multiply_VectorFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_GM_Payload_WidowMaker_C_K2_NativeDelayCallback, CallFunc_Add_VectorVector_ReturnValue) == 0x000130, "Member 'BP_GM_Payload_WidowMaker_C_K2_NativeDelayCallback::CallFunc_Add_VectorVector_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_GM_Payload_WidowMaker_C_K2_NativeDelayCallback, CallFunc_Array_Length_ReturnValue) == 0x00013C, "Member 'BP_GM_Payload_WidowMaker_C_K2_NativeDelayCallback::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_GM_Payload_WidowMaker_C_K2_NativeDelayCallback, CallFunc_Less_IntInt_ReturnValue) == 0x000140, "Member 'BP_GM_Payload_WidowMaker_C_K2_NativeDelayCallback::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_GM_Payload_WidowMaker_C_K2_NativeDelayCallback, CallFunc_Conv_FloatToForceSelection_ReturnValue) == 0x000148, "Member 'BP_GM_Payload_WidowMaker_C_K2_NativeDelayCallback::CallFunc_Conv_FloatToForceSelection_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_GM_Payload_WidowMaker_C_K2_NativeDelayCallback, CallFunc_GetOwner_ReturnValue) == 0x000168, "Member 'BP_GM_Payload_WidowMaker_C_K2_NativeDelayCallback::CallFunc_GetOwner_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_GM_Payload_WidowMaker_C_K2_NativeDelayCallback, CallFunc_K2_GetActorLocation_ReturnValue1) == 0x000170, "Member 'BP_GM_Payload_WidowMaker_C_K2_NativeDelayCallback::CallFunc_K2_GetActorLocation_ReturnValue1' has a wrong offset!");
static_assert(offsetof(BP_GM_Payload_WidowMaker_C_K2_NativeDelayCallback, CallFunc_BreakVector_X) == 0x00017C, "Member 'BP_GM_Payload_WidowMaker_C_K2_NativeDelayCallback::CallFunc_BreakVector_X' has a wrong offset!");
static_assert(offsetof(BP_GM_Payload_WidowMaker_C_K2_NativeDelayCallback, CallFunc_BreakVector_Y) == 0x000180, "Member 'BP_GM_Payload_WidowMaker_C_K2_NativeDelayCallback::CallFunc_BreakVector_Y' has a wrong offset!");
static_assert(offsetof(BP_GM_Payload_WidowMaker_C_K2_NativeDelayCallback, CallFunc_BreakVector_Z) == 0x000184, "Member 'BP_GM_Payload_WidowMaker_C_K2_NativeDelayCallback::CallFunc_BreakVector_Z' has a wrong offset!");
static_assert(offsetof(BP_GM_Payload_WidowMaker_C_K2_NativeDelayCallback, CallFunc_Add_FloatFloat_ReturnValue) == 0x000188, "Member 'BP_GM_Payload_WidowMaker_C_K2_NativeDelayCallback::CallFunc_Add_FloatFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_GM_Payload_WidowMaker_C_K2_NativeDelayCallback, CallFunc_MakeVector_ReturnValue) == 0x00018C, "Member 'BP_GM_Payload_WidowMaker_C_K2_NativeDelayCallback::CallFunc_MakeVector_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_GM_Payload_WidowMaker_C_K2_NativeDelayCallback, K2Node_MakeStruct_LightProjectileInitializationData) == 0x000198, "Member 'BP_GM_Payload_WidowMaker_C_K2_NativeDelayCallback::K2Node_MakeStruct_LightProjectileInitializationData' has a wrong offset!");

// Function BP_GM_Payload_WidowMaker.BP_GM_Payload_WidowMaker_C.K2_StuckGrenadeOverlapped
// 0x0030 (0x0030 - 0x0000)
struct BP_GM_Payload_WidowMaker_C_K2_StuckGrenadeOverlapped final
{
public:
	class AGrenade*                               Grenade;                                           // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AGrenadeMod*                            GrenadeMod;                                        // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 OverlappedActor;                                   // 0x0010(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_K2_EvaluateConditionType_ReturnValue;     // 0x0018(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsAlive_ReturnValue;                      // 0x0019(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1A[0x6];                                       // 0x001A(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class UGrenadeHomingComponent*                CallFunc_GetHomingComponent_ReturnValue;           // 0x0020(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanAND_ReturnValue;                   // 0x0028(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(BP_GM_Payload_WidowMaker_C_K2_StuckGrenadeOverlapped) == 0x000008, "Wrong alignment on BP_GM_Payload_WidowMaker_C_K2_StuckGrenadeOverlapped");
static_assert(sizeof(BP_GM_Payload_WidowMaker_C_K2_StuckGrenadeOverlapped) == 0x000030, "Wrong size on BP_GM_Payload_WidowMaker_C_K2_StuckGrenadeOverlapped");
static_assert(offsetof(BP_GM_Payload_WidowMaker_C_K2_StuckGrenadeOverlapped, Grenade) == 0x000000, "Member 'BP_GM_Payload_WidowMaker_C_K2_StuckGrenadeOverlapped::Grenade' has a wrong offset!");
static_assert(offsetof(BP_GM_Payload_WidowMaker_C_K2_StuckGrenadeOverlapped, GrenadeMod) == 0x000008, "Member 'BP_GM_Payload_WidowMaker_C_K2_StuckGrenadeOverlapped::GrenadeMod' has a wrong offset!");
static_assert(offsetof(BP_GM_Payload_WidowMaker_C_K2_StuckGrenadeOverlapped, OverlappedActor) == 0x000010, "Member 'BP_GM_Payload_WidowMaker_C_K2_StuckGrenadeOverlapped::OverlappedActor' has a wrong offset!");
static_assert(offsetof(BP_GM_Payload_WidowMaker_C_K2_StuckGrenadeOverlapped, CallFunc_K2_EvaluateConditionType_ReturnValue) == 0x000018, "Member 'BP_GM_Payload_WidowMaker_C_K2_StuckGrenadeOverlapped::CallFunc_K2_EvaluateConditionType_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_GM_Payload_WidowMaker_C_K2_StuckGrenadeOverlapped, CallFunc_IsAlive_ReturnValue) == 0x000019, "Member 'BP_GM_Payload_WidowMaker_C_K2_StuckGrenadeOverlapped::CallFunc_IsAlive_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_GM_Payload_WidowMaker_C_K2_StuckGrenadeOverlapped, CallFunc_GetHomingComponent_ReturnValue) == 0x000020, "Member 'BP_GM_Payload_WidowMaker_C_K2_StuckGrenadeOverlapped::CallFunc_GetHomingComponent_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_GM_Payload_WidowMaker_C_K2_StuckGrenadeOverlapped, CallFunc_BooleanAND_ReturnValue) == 0x000028, "Member 'BP_GM_Payload_WidowMaker_C_K2_StuckGrenadeOverlapped::CallFunc_BooleanAND_ReturnValue' has a wrong offset!");

// Function BP_GM_Payload_WidowMaker.BP_GM_Payload_WidowMaker_C.K2_GrenadeStuckTo
// 0x00E0 (0x00E0 - 0x0000)
struct BP_GM_Payload_WidowMaker_C_K2_GrenadeStuckTo final
{
public:
	class AGrenade*                               Grenade;                                           // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AGrenadeMod*                            GrenadeMod;                                        // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 StickTarget;                                       // 0x0010(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FPayloadInstanceData                   InstanceData;                                      // 0x0018(0x0030)(BlueprintVisible, Parm, OutParm, ReferenceParm, NoDestructor)
	struct FHitResult                             HitResult;                                         // 0x0048(0x0090)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, IsPlainOldData, NoDestructor, ContainsInstancedReference)
	class UGrenadeHomingComponent*                CallFunc_GetHomingComponent_ReturnValue;           // 0x00D8(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_GM_Payload_WidowMaker_C_K2_GrenadeStuckTo) == 0x000008, "Wrong alignment on BP_GM_Payload_WidowMaker_C_K2_GrenadeStuckTo");
static_assert(sizeof(BP_GM_Payload_WidowMaker_C_K2_GrenadeStuckTo) == 0x0000E0, "Wrong size on BP_GM_Payload_WidowMaker_C_K2_GrenadeStuckTo");
static_assert(offsetof(BP_GM_Payload_WidowMaker_C_K2_GrenadeStuckTo, Grenade) == 0x000000, "Member 'BP_GM_Payload_WidowMaker_C_K2_GrenadeStuckTo::Grenade' has a wrong offset!");
static_assert(offsetof(BP_GM_Payload_WidowMaker_C_K2_GrenadeStuckTo, GrenadeMod) == 0x000008, "Member 'BP_GM_Payload_WidowMaker_C_K2_GrenadeStuckTo::GrenadeMod' has a wrong offset!");
static_assert(offsetof(BP_GM_Payload_WidowMaker_C_K2_GrenadeStuckTo, StickTarget) == 0x000010, "Member 'BP_GM_Payload_WidowMaker_C_K2_GrenadeStuckTo::StickTarget' has a wrong offset!");
static_assert(offsetof(BP_GM_Payload_WidowMaker_C_K2_GrenadeStuckTo, InstanceData) == 0x000018, "Member 'BP_GM_Payload_WidowMaker_C_K2_GrenadeStuckTo::InstanceData' has a wrong offset!");
static_assert(offsetof(BP_GM_Payload_WidowMaker_C_K2_GrenadeStuckTo, HitResult) == 0x000048, "Member 'BP_GM_Payload_WidowMaker_C_K2_GrenadeStuckTo::HitResult' has a wrong offset!");
static_assert(offsetof(BP_GM_Payload_WidowMaker_C_K2_GrenadeStuckTo, CallFunc_GetHomingComponent_ReturnValue) == 0x0000D8, "Member 'BP_GM_Payload_WidowMaker_C_K2_GrenadeStuckTo::CallFunc_GetHomingComponent_ReturnValue' has a wrong offset!");

// Function BP_GM_Payload_WidowMaker.BP_GM_Payload_WidowMaker_C.K2_GrenadeInitialized
// 0x0070 (0x0070 - 0x0000)
struct BP_GM_Payload_WidowMaker_C_K2_GrenadeInitialized final
{
public:
	class AGrenade*                               Grenade;                                           // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AGrenadeMod*                            GrenadeMod;                                        // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FPayloadInstanceData                   InstanceData;                                      // 0x0010(0x0030)(BlueprintVisible, Parm, OutParm, ReferenceParm, NoDestructor)
	struct FGrenadeChildGenerationData            CallFunc_GetChildOffset_ReturnValue;               // 0x0040(0x0028)(NoDestructor)
	bool                                          CallFunc_Greater_IntInt_ReturnValue;               // 0x0068(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_69[0x3];                                       // 0x0069(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_Multiply_FloatFloat_ReturnValue;          // 0x006C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_GM_Payload_WidowMaker_C_K2_GrenadeInitialized) == 0x000008, "Wrong alignment on BP_GM_Payload_WidowMaker_C_K2_GrenadeInitialized");
static_assert(sizeof(BP_GM_Payload_WidowMaker_C_K2_GrenadeInitialized) == 0x000070, "Wrong size on BP_GM_Payload_WidowMaker_C_K2_GrenadeInitialized");
static_assert(offsetof(BP_GM_Payload_WidowMaker_C_K2_GrenadeInitialized, Grenade) == 0x000000, "Member 'BP_GM_Payload_WidowMaker_C_K2_GrenadeInitialized::Grenade' has a wrong offset!");
static_assert(offsetof(BP_GM_Payload_WidowMaker_C_K2_GrenadeInitialized, GrenadeMod) == 0x000008, "Member 'BP_GM_Payload_WidowMaker_C_K2_GrenadeInitialized::GrenadeMod' has a wrong offset!");
static_assert(offsetof(BP_GM_Payload_WidowMaker_C_K2_GrenadeInitialized, InstanceData) == 0x000010, "Member 'BP_GM_Payload_WidowMaker_C_K2_GrenadeInitialized::InstanceData' has a wrong offset!");
static_assert(offsetof(BP_GM_Payload_WidowMaker_C_K2_GrenadeInitialized, CallFunc_GetChildOffset_ReturnValue) == 0x000040, "Member 'BP_GM_Payload_WidowMaker_C_K2_GrenadeInitialized::CallFunc_GetChildOffset_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_GM_Payload_WidowMaker_C_K2_GrenadeInitialized, CallFunc_Greater_IntInt_ReturnValue) == 0x000068, "Member 'BP_GM_Payload_WidowMaker_C_K2_GrenadeInitialized::CallFunc_Greater_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_GM_Payload_WidowMaker_C_K2_GrenadeInitialized, CallFunc_Multiply_FloatFloat_ReturnValue) == 0x00006C, "Member 'BP_GM_Payload_WidowMaker_C_K2_GrenadeInitialized::CallFunc_Multiply_FloatFloat_ReturnValue' has a wrong offset!");

}

