#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_IO_EmergencyLight

#include "Basic.hpp"

#include "BP_IO_EmergencyLight_classes.hpp"
#include "BP_IO_EmergencyLight_parameters.hpp"


namespace SDK
{

// Function BP_IO_EmergencyLight.BP_IO_EmergencyLight_C.SetLightColor
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   ColorArrayIndex                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_IO_EmergencyLight_C::SetLightColor(int32 ColorArrayIndex)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_IO_EmergencyLight_C", "SetLightColor");

	Params::BP_IO_EmergencyLight_C_SetLightColor Parms{};

	Parms.ColorArrayIndex = ColorArrayIndex;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_IO_EmergencyLight.BP_IO_EmergencyLight_C.UserConstructionScript
// (Event, Public, BlueprintCallable, BlueprintEvent)

void ABP_IO_EmergencyLight_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_IO_EmergencyLight_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_IO_EmergencyLight.BP_IO_EmergencyLight_C.Timeline_0__FinishedFunc
// (BlueprintEvent)

void ABP_IO_EmergencyLight_C::Timeline_0__FinishedFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_IO_EmergencyLight_C", "Timeline_0__FinishedFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_IO_EmergencyLight.BP_IO_EmergencyLight_C.Timeline_0__UpdateFunc
// (BlueprintEvent)

void ABP_IO_EmergencyLight_C::Timeline_0__UpdateFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_IO_EmergencyLight_C", "Timeline_0__UpdateFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_IO_EmergencyLight.BP_IO_EmergencyLight_C.__UserState_State_Color_3
// (BlueprintEvent)
// Parameters:
// bool                                    bFromLoad                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ABP_IO_EmergencyLight_C::__UserState_State_Color_3(bool bFromLoad)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_IO_EmergencyLight_C", "__UserState_State_Color_3");

	Params::BP_IO_EmergencyLight_C___UserState_State_Color_3 Parms{};

	Parms.bFromLoad = bFromLoad;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_IO_EmergencyLight.BP_IO_EmergencyLight_C.__UserState_State_Color_4
// (BlueprintEvent)
// Parameters:
// bool                                    bFromLoad                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ABP_IO_EmergencyLight_C::__UserState_State_Color_4(bool bFromLoad)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_IO_EmergencyLight_C", "__UserState_State_Color_4");

	Params::BP_IO_EmergencyLight_C___UserState_State_Color_4 Parms{};

	Parms.bFromLoad = bFromLoad;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_IO_EmergencyLight.BP_IO_EmergencyLight_C.Preview_Color_01
// (BlueprintCallable, BlueprintEvent)

void ABP_IO_EmergencyLight_C::Preview_Color_01()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_IO_EmergencyLight_C", "Preview_Color_01");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_IO_EmergencyLight.BP_IO_EmergencyLight_C.Preview_Color_02
// (BlueprintCallable, BlueprintEvent)

void ABP_IO_EmergencyLight_C::Preview_Color_02()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_IO_EmergencyLight_C", "Preview_Color_02");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_IO_EmergencyLight.BP_IO_EmergencyLight_C.Preview_Color_03
// (BlueprintCallable, BlueprintEvent)

void ABP_IO_EmergencyLight_C::Preview_Color_03()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_IO_EmergencyLight_C", "Preview_Color_03");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_IO_EmergencyLight.BP_IO_EmergencyLight_C.Preview_Color_04
// (BlueprintCallable, BlueprintEvent)

void ABP_IO_EmergencyLight_C::Preview_Color_04()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_IO_EmergencyLight_C", "Preview_Color_04");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_IO_EmergencyLight.BP_IO_EmergencyLight_C.Preview_Color_05
// (BlueprintCallable, BlueprintEvent)

void ABP_IO_EmergencyLight_C::Preview_Color_05()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_IO_EmergencyLight_C", "Preview_Color_05");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_IO_EmergencyLight.BP_IO_EmergencyLight_C.__UserState_State_Behavior_0
// (BlueprintEvent)
// Parameters:
// bool                                    bFromLoad                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ABP_IO_EmergencyLight_C::__UserState_State_Behavior_0(bool bFromLoad)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_IO_EmergencyLight_C", "__UserState_State_Behavior_0");

	Params::BP_IO_EmergencyLight_C___UserState_State_Behavior_0 Parms{};

	Parms.bFromLoad = bFromLoad;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_IO_EmergencyLight.BP_IO_EmergencyLight_C.__UserState_State_Behavior_2
// (BlueprintEvent)
// Parameters:
// bool                                    bFromLoad                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ABP_IO_EmergencyLight_C::__UserState_State_Behavior_2(bool bFromLoad)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_IO_EmergencyLight_C", "__UserState_State_Behavior_2");

	Params::BP_IO_EmergencyLight_C___UserState_State_Behavior_2 Parms{};

	Parms.bFromLoad = bFromLoad;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_IO_EmergencyLight.BP_IO_EmergencyLight_C.__UserState_State_Behavior_3
// (BlueprintEvent)
// Parameters:
// bool                                    bFromLoad                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ABP_IO_EmergencyLight_C::__UserState_State_Behavior_3(bool bFromLoad)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_IO_EmergencyLight_C", "__UserState_State_Behavior_3");

	Params::BP_IO_EmergencyLight_C___UserState_State_Behavior_3 Parms{};

	Parms.bFromLoad = bFromLoad;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_IO_EmergencyLight.BP_IO_EmergencyLight_C.Preview_BehaviorNone
// (BlueprintCallable, BlueprintEvent)

void ABP_IO_EmergencyLight_C::Preview_BehaviorNone()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_IO_EmergencyLight_C", "Preview_BehaviorNone");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_IO_EmergencyLight.BP_IO_EmergencyLight_C.Preview_BehaviorPulse
// (BlueprintCallable, BlueprintEvent)

void ABP_IO_EmergencyLight_C::Preview_BehaviorPulse()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_IO_EmergencyLight_C", "Preview_BehaviorPulse");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_IO_EmergencyLight.BP_IO_EmergencyLight_C.Preview_BehaviorPulseAndSpin
// (BlueprintCallable, BlueprintEvent)

void ABP_IO_EmergencyLight_C::Preview_BehaviorPulseAndSpin()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_IO_EmergencyLight_C", "Preview_BehaviorPulseAndSpin");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_IO_EmergencyLight.BP_IO_EmergencyLight_C.__UserState_State_Behavior_1
// (BlueprintEvent)
// Parameters:
// bool                                    bFromLoad                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ABP_IO_EmergencyLight_C::__UserState_State_Behavior_1(bool bFromLoad)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_IO_EmergencyLight_C", "__UserState_State_Behavior_1");

	Params::BP_IO_EmergencyLight_C___UserState_State_Behavior_1 Parms{};

	Parms.bFromLoad = bFromLoad;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_IO_EmergencyLight.BP_IO_EmergencyLight_C.PreviewBehavior_On-NoMovement
// (BlueprintCallable, BlueprintEvent)

void ABP_IO_EmergencyLight_C::PreviewBehavior_OnMinusNoMovement()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_IO_EmergencyLight_C", "PreviewBehavior_On-NoMovement");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_IO_EmergencyLight.BP_IO_EmergencyLight_C.__UserState_State_Color_2
// (BlueprintEvent)
// Parameters:
// bool                                    bFromLoad                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ABP_IO_EmergencyLight_C::__UserState_State_Color_2(bool bFromLoad)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_IO_EmergencyLight_C", "__UserState_State_Color_2");

	Params::BP_IO_EmergencyLight_C___UserState_State_Color_2 Parms{};

	Parms.bFromLoad = bFromLoad;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_IO_EmergencyLight.BP_IO_EmergencyLight_C.__UserState_State_Color_1
// (BlueprintEvent)
// Parameters:
// bool                                    bFromLoad                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ABP_IO_EmergencyLight_C::__UserState_State_Color_1(bool bFromLoad)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_IO_EmergencyLight_C", "__UserState_State_Color_1");

	Params::BP_IO_EmergencyLight_C___UserState_State_Color_1 Parms{};

	Parms.bFromLoad = bFromLoad;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_IO_EmergencyLight.BP_IO_EmergencyLight_C.__UserState_State_Color_0
// (BlueprintEvent)
// Parameters:
// bool                                    bFromLoad                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ABP_IO_EmergencyLight_C::__UserState_State_Color_0(bool bFromLoad)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_IO_EmergencyLight_C", "__UserState_State_Color_0");

	Params::BP_IO_EmergencyLight_C___UserState_State_Color_0 Parms{};

	Parms.bFromLoad = bFromLoad;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_IO_EmergencyLight.BP_IO_EmergencyLight_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_IO_EmergencyLight_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_IO_EmergencyLight_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_IO_EmergencyLight.BP_IO_EmergencyLight_C.__UserState_State_SirenAudio_0
// (BlueprintEvent)
// Parameters:
// bool                                    bFromLoad                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ABP_IO_EmergencyLight_C::__UserState_State_SirenAudio_0(bool bFromLoad)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_IO_EmergencyLight_C", "__UserState_State_SirenAudio_0");

	Params::BP_IO_EmergencyLight_C___UserState_State_SirenAudio_0 Parms{};

	Parms.bFromLoad = bFromLoad;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_IO_EmergencyLight.BP_IO_EmergencyLight_C.__UserState_State_SirenAudio_1
// (BlueprintEvent)
// Parameters:
// bool                                    bFromLoad                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ABP_IO_EmergencyLight_C::__UserState_State_SirenAudio_1(bool bFromLoad)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_IO_EmergencyLight_C", "__UserState_State_SirenAudio_1");

	Params::BP_IO_EmergencyLight_C___UserState_State_SirenAudio_1 Parms{};

	Parms.bFromLoad = bFromLoad;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_IO_EmergencyLight.BP_IO_EmergencyLight_C.SetColorState
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   Color_Array_Index                                      (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_IO_EmergencyLight_C::SetColorState(int32 Color_Array_Index)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_IO_EmergencyLight_C", "SetColorState");

	Params::BP_IO_EmergencyLight_C_SetColorState Parms{};

	Parms.Color_Array_Index = Color_Array_Index;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_IO_EmergencyLight.BP_IO_EmergencyLight_C.SetEmergencyLightColorState
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// EnumState_EmergencyLight_Color          StateColorEnum                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_IO_EmergencyLight_C::SetEmergencyLightColorState(EnumState_EmergencyLight_Color StateColorEnum)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_IO_EmergencyLight_C", "SetEmergencyLightColorState");

	Params::BP_IO_EmergencyLight_C_SetEmergencyLightColorState Parms{};

	Parms.StateColorEnum = StateColorEnum;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_IO_EmergencyLight.BP_IO_EmergencyLight_C.ExecuteUbergraph_BP_IO_EmergencyLight
// (HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_IO_EmergencyLight_C::ExecuteUbergraph_BP_IO_EmergencyLight(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_IO_EmergencyLight_C", "ExecuteUbergraph_BP_IO_EmergencyLight");

	Params::BP_IO_EmergencyLight_C_ExecuteUbergraph_BP_IO_EmergencyLight Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

