#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_MAL_ElemPrimary_00_Master

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"
#include "GbxInventory_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_MAL_ElemPrimary_00_Master.BP_MAL_ElemPrimary_00_Master_C
// 0x0020 (0x0058 - 0x0038)
class UBP_MAL_ElemPrimary_00_Master_C : public UInventoryAspectData
{
public:
	struct FLinearColor                           BaseColor;                                         // 0x0038(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FLinearColor                           HighlightColor;                                    // 0x0048(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	class FString K2_GetFriendlyDescription() const;
	void K2_OnApplyAspect(class AActor* InventoryActor, const class UInventoryBalanceStateComponent* InventoryBalanceState) const;
	void K2_CloneAppearance(class AActor* CloneActor, class AActor* InventoryActor, const class UInventoryBalanceStateComponent* InventoryBalanceState) const;

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_MAL_ElemPrimary_00_Master_C">();
	}
	static class UBP_MAL_ElemPrimary_00_Master_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_MAL_ElemPrimary_00_Master_C>();
	}
};
static_assert(alignof(UBP_MAL_ElemPrimary_00_Master_C) == 0x000008, "Wrong alignment on UBP_MAL_ElemPrimary_00_Master_C");
static_assert(sizeof(UBP_MAL_ElemPrimary_00_Master_C) == 0x000058, "Wrong size on UBP_MAL_ElemPrimary_00_Master_C");
static_assert(offsetof(UBP_MAL_ElemPrimary_00_Master_C, BaseColor) == 0x000038, "Member 'UBP_MAL_ElemPrimary_00_Master_C::BaseColor' has a wrong offset!");
static_assert(offsetof(UBP_MAL_ElemPrimary_00_Master_C, HighlightColor) == 0x000048, "Member 'UBP_MAL_ElemPrimary_00_Master_C::HighlightColor' has a wrong offset!");

}

