#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPAmmoItem_SMG

#include "Basic.hpp"

#include "OakGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BPAmmoItem_SMG.BPAmmoItem_SMG_C
// 0x0000 (0x04A8 - 0x04A8)
class ABPAmmoItem_SMG_C final : public AOakInventoryAmmoItem
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BPAmmoItem_SMG_C">();
	}
	static class ABPAmmoItem_SMG_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABPAmmoItem_SMG_C>();
	}
};
static_assert(alignof(ABPAmmoItem_SMG_C) == 0x000008, "Wrong alignment on ABPAmmoItem_SMG_C");
static_assert(sizeof(ABPAmmoItem_SMG_C) == 0x0004A8, "Wrong size on ABPAmmoItem_SMG_C");

}

