#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPAnim_SR_JAK

#include "Basic.hpp"

#include "BPAnim_SR_JAK_classes.hpp"
#include "BPAnim_SR_JAK_parameters.hpp"


namespace SDK
{

// Function BPAnim_SR_JAK.BPAnim_SR_JAK_C.EvaluateGraphExposedInputs_ExecuteUbergraph_BPAnim_SR_JAK_AnimGraphNode_SequenceEvaluator_02E50AB34D74AB6CD463B2B9500A4B9D
// (BlueprintEvent)

void UBPAnim_SR_JAK_C::EvaluateGraphExposedInputs_ExecuteUbergraph_BPAnim_SR_JAK_AnimGraphNode_SequenceEvaluator_02E50AB34D74AB6CD463B2B9500A4B9D()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPAnim_SR_JAK_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_BPAnim_SR_JAK_AnimGraphNode_SequenceEvaluator_02E50AB34D74AB6CD463B2B9500A4B9D");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BPAnim_SR_JAK.BPAnim_SR_JAK_C.EvaluateGraphExposedInputs_ExecuteUbergraph_BPAnim_SR_JAK_AnimGraphNode_SequenceEvaluator_CF0573074FFFD9ABECDD7EA02A869DB2
// (BlueprintEvent)

void UBPAnim_SR_JAK_C::EvaluateGraphExposedInputs_ExecuteUbergraph_BPAnim_SR_JAK_AnimGraphNode_SequenceEvaluator_CF0573074FFFD9ABECDD7EA02A869DB2()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPAnim_SR_JAK_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_BPAnim_SR_JAK_AnimGraphNode_SequenceEvaluator_CF0573074FFFD9ABECDD7EA02A869DB2");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BPAnim_SR_JAK.BPAnim_SR_JAK_C.ExecuteUbergraph_BPAnim_SR_JAK
// ()
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBPAnim_SR_JAK_C::ExecuteUbergraph_BPAnim_SR_JAK(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPAnim_SR_JAK_C", "ExecuteUbergraph_BPAnim_SR_JAK");

	Params::BPAnim_SR_JAK_C_ExecuteUbergraph_BPAnim_SR_JAK Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

