#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPAnim_HW_VLA

#include "Basic.hpp"

#include "BPAnim_HW_VLA_classes.hpp"
#include "BPAnim_HW_VLA_parameters.hpp"


namespace SDK
{

// Function BPAnim_HW_VLA.BPAnim_HW_VLA_C.ExecuteUbergraph_BPAnim_HW_VLA
// ()
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBPAnim_HW_VLA_C::ExecuteUbergraph_BPAnim_HW_VLA(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPAnim_HW_VLA_C", "ExecuteUbergraph_BPAnim_HW_VLA");

	Params::BPAnim_HW_VLA_C_ExecuteUbergraph_BPAnim_HW_VLA Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BPAnim_HW_VLA.BPAnim_HW_VLA_C.BlueprintSwitchedMode
// (Event, Protected, BlueprintEvent)
// Parameters:
// int32                                   NewMode                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBPAnim_HW_VLA_C::BlueprintSwitchedMode(int32 NewMode)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPAnim_HW_VLA_C", "BlueprintSwitchedMode");

	Params::BPAnim_HW_VLA_C_BlueprintSwitchedMode Parms{};

	Parms.NewMode = NewMode;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BPAnim_HW_VLA.BPAnim_HW_VLA_C.BlueprintInitializeAnimation
// (Event, Public, BlueprintEvent)

void UBPAnim_HW_VLA_C::BlueprintInitializeAnimation()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPAnim_HW_VLA_C", "BlueprintInitializeAnimation");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BPAnim_HW_VLA.BPAnim_HW_VLA_C.EvaluateGraphExposedInputs_ExecuteUbergraph_BPAnim_HW_VLA_AnimGraphNode_SequenceEvaluator_FFBDA08E4295C7EECEA95B9044BB5FC8
// (BlueprintEvent)

void UBPAnim_HW_VLA_C::EvaluateGraphExposedInputs_ExecuteUbergraph_BPAnim_HW_VLA_AnimGraphNode_SequenceEvaluator_FFBDA08E4295C7EECEA95B9044BB5FC8()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPAnim_HW_VLA_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_BPAnim_HW_VLA_AnimGraphNode_SequenceEvaluator_FFBDA08E4295C7EECEA95B9044BB5FC8");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BPAnim_HW_VLA.BPAnim_HW_VLA_C.EvaluateGraphExposedInputs_ExecuteUbergraph_BPAnim_HW_VLA_AnimGraphNode_SequenceEvaluator_DD8E2BA748CADFB3FC227CB8DD499581
// (BlueprintEvent)

void UBPAnim_HW_VLA_C::EvaluateGraphExposedInputs_ExecuteUbergraph_BPAnim_HW_VLA_AnimGraphNode_SequenceEvaluator_DD8E2BA748CADFB3FC227CB8DD499581()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPAnim_HW_VLA_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_BPAnim_HW_VLA_AnimGraphNode_SequenceEvaluator_DD8E2BA748CADFB3FC227CB8DD499581");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BPAnim_HW_VLA.BPAnim_HW_VLA_C.EvaluateGraphExposedInputs_ExecuteUbergraph_BPAnim_HW_VLA_AnimGraphNode_SequenceEvaluator_80B973BA490D96EC1A6863BBAAFE80D0
// (BlueprintEvent)

void UBPAnim_HW_VLA_C::EvaluateGraphExposedInputs_ExecuteUbergraph_BPAnim_HW_VLA_AnimGraphNode_SequenceEvaluator_80B973BA490D96EC1A6863BBAAFE80D0()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPAnim_HW_VLA_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_BPAnim_HW_VLA_AnimGraphNode_SequenceEvaluator_80B973BA490D96EC1A6863BBAAFE80D0");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BPAnim_HW_VLA.BPAnim_HW_VLA_C.UpdateIdleAnim
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   UseMode                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBPAnim_HW_VLA_C::UpdateIdleAnim(int32 UseMode)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPAnim_HW_VLA_C", "UpdateIdleAnim");

	Params::BPAnim_HW_VLA_C_UpdateIdleAnim Parms{};

	Parms.UseMode = UseMode;

	UObject::ProcessEvent(Func, &Parms);
}

}

