#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPChar_PetSpiderant_Evo2_King

#include "Basic.hpp"


namespace SDK::Params
{

// Function BPChar_PetSpiderant_Evo2_King.BPChar_PetSpiderant_Evo2_King_C.ExecuteUbergraph_BPChar_PetSpiderant_Evo2_King
// 0x0004 (0x0004 - 0x0000)
struct BPChar_PetSpiderant_Evo2_King_C_ExecuteUbergraph_BPChar_PetSpiderant_Evo2_King final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BPChar_PetSpiderant_Evo2_King_C_ExecuteUbergraph_BPChar_PetSpiderant_Evo2_King) == 0x000004, "Wrong alignment on BPChar_PetSpiderant_Evo2_King_C_ExecuteUbergraph_BPChar_PetSpiderant_Evo2_King");
static_assert(sizeof(BPChar_PetSpiderant_Evo2_King_C_ExecuteUbergraph_BPChar_PetSpiderant_Evo2_King) == 0x000004, "Wrong size on BPChar_PetSpiderant_Evo2_King_C_ExecuteUbergraph_BPChar_PetSpiderant_Evo2_King");
static_assert(offsetof(BPChar_PetSpiderant_Evo2_King_C_ExecuteUbergraph_BPChar_PetSpiderant_Evo2_King, EntryPoint) == 0x000000, "Member 'BPChar_PetSpiderant_Evo2_King_C_ExecuteUbergraph_BPChar_PetSpiderant_Evo2_King::EntryPoint' has a wrong offset!");

}

