#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPChar_ServiceBot

#include "Basic.hpp"

#include "BPChar_ServiceBot_classes.hpp"
#include "BPChar_ServiceBot_parameters.hpp"


namespace SDK
{

// Function BPChar_ServiceBot.BPChar_ServiceBot_C.ExecuteUbergraph_BPChar_ServiceBot
// (HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABPChar_ServiceBot_C::ExecuteUbergraph_BPChar_ServiceBot(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPChar_ServiceBot_C", "ExecuteUbergraph_BPChar_ServiceBot");

	Params::BPChar_ServiceBot_C_ExecuteUbergraph_BPChar_ServiceBot Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BPChar_ServiceBot.BPChar_ServiceBot_C.ServiceBot_TargetChanged
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AActor*                           TargetActor                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABPChar_ServiceBot_C::ServiceBot_TargetChanged(class AActor* TargetActor)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPChar_ServiceBot_C", "ServiceBot_TargetChanged");

	Params::BPChar_ServiceBot_C_ServiceBot_TargetChanged Parms{};

	Parms.TargetActor = TargetActor;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BPChar_ServiceBot.BPChar_ServiceBot_C.ServiceBot_SuicideTimer
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    Start                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ABPChar_ServiceBot_C::ServiceBot_SuicideTimer(bool Start)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPChar_ServiceBot_C", "ServiceBot_SuicideTimer");

	Params::BPChar_ServiceBot_C_ServiceBot_SuicideTimer Parms{};

	Parms.Start = Start;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BPChar_ServiceBot.BPChar_ServiceBot_C.CE_Suicide
// (BlueprintCallable, BlueprintEvent)

void ABPChar_ServiceBot_C::CE_Suicide()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPChar_ServiceBot_C", "CE_Suicide");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BPChar_ServiceBot.BPChar_ServiceBot_C.AssignDominantPieces
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    RightArmDominant_0                                     (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// bool                                    LeftArmDominant_0                                      (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// bool                                    HeadDominant_0                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ABPChar_ServiceBot_C::AssignDominantPieces(bool RightArmDominant_0, bool LeftArmDominant_0, bool HeadDominant_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPChar_ServiceBot_C", "AssignDominantPieces");

	Params::BPChar_ServiceBot_C_AssignDominantPieces Parms{};

	Parms.RightArmDominant_0 = RightArmDominant_0;
	Parms.LeftArmDominant_0 = LeftArmDominant_0;
	Parms.HeadDominant_0 = HeadDominant_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BPChar_ServiceBot.BPChar_ServiceBot_C.ServiceBot_Suicide
// (Public, BlueprintCallable, BlueprintEvent)

void ABPChar_ServiceBot_C::ServiceBot_Suicide()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPChar_ServiceBot_C", "ServiceBot_Suicide");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BPChar_ServiceBot.BPChar_ServiceBot_C.ServiceBot_ManageUIName
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UGbxUIName*                       UIName                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABPChar_ServiceBot_C::ServiceBot_ManageUIName(class UGbxUIName* UIName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPChar_ServiceBot_C", "ServiceBot_ManageUIName");

	Params::BPChar_ServiceBot_C_ServiceBot_ManageUIName Parms{};

	Parms.UIName = UIName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BPChar_ServiceBot.BPChar_ServiceBot_C.ReceiveEndPlay
// (Event, Public, BlueprintEvent)
// Parameters:
// EEndPlayReason                          EndPlayReason                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABPChar_ServiceBot_C::ReceiveEndPlay(EEndPlayReason EndPlayReason)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPChar_ServiceBot_C", "ReceiveEndPlay");

	Params::BPChar_ServiceBot_C_ReceiveEndPlay Parms{};

	Parms.EndPlayReason = EndPlayReason;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BPChar_ServiceBot.BPChar_ServiceBot_C.DesignateAttachedPieces
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    HasHead_0                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// bool                                    HasRightArm_0                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// bool                                    HasLeftArm_0                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ABPChar_ServiceBot_C::DesignateAttachedPieces(bool HasHead_0, bool HasRightArm_0, bool HasLeftArm_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPChar_ServiceBot_C", "DesignateAttachedPieces");

	Params::BPChar_ServiceBot_C_DesignateAttachedPieces Parms{};

	Parms.HasHead_0 = HasHead_0;
	Parms.HasRightArm_0 = HasRightArm_0;
	Parms.HasLeftArm_0 = HasLeftArm_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BPChar_ServiceBot.BPChar_ServiceBot_C.BackupAttack
// (Public, BlueprintCallable, BlueprintEvent)

void ABPChar_ServiceBot_C::BackupAttack()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPChar_ServiceBot_C", "BackupAttack");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BPChar_ServiceBot.BPChar_ServiceBot_C.BndEvt__SmartObject_K2Node_ComponentBoundEvent_1_SmartObjectUsageEvent__DelegateSignature_BPChar_ServiceBot
// (BlueprintEvent)
// Parameters:
// class AController*                      Controller_0                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FGameplayTag                     ActionTag                                              (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor, HasGetValueTypeHash)

void ABPChar_ServiceBot_C::BndEvt__SmartObject_K2Node_ComponentBoundEvent_1_SmartObjectUsageEvent__DelegateSignature_BPChar_ServiceBot(class AController* Controller_0, const struct FGameplayTag& ActionTag)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPChar_ServiceBot_C", "BndEvt__SmartObject_K2Node_ComponentBoundEvent_1_SmartObjectUsageEvent__DelegateSignature_BPChar_ServiceBot");

	Params::BPChar_ServiceBot_C_BndEvt__SmartObject_K2Node_ComponentBoundEvent_1_SmartObjectUsageEvent__DelegateSignature_BPChar_ServiceBot Parms{};

	Parms.Controller_0 = Controller_0;
	Parms.ActionTag = std::move(ActionTag);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BPChar_ServiceBot.BPChar_ServiceBot_C.BndEvt__OakDamageComponent_K2Node_ComponentBoundEvent_0_DamageCompDiedDelegate__DelegateSignature_BPChar_ServiceBot
// (BlueprintEvent)
// Parameters:
// class AActor*                           DamageReceiver                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class AActor*                           DamageCauser                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABPChar_ServiceBot_C::BndEvt__OakDamageComponent_K2Node_ComponentBoundEvent_0_DamageCompDiedDelegate__DelegateSignature_BPChar_ServiceBot(class AActor* DamageReceiver, class AActor* DamageCauser)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPChar_ServiceBot_C", "BndEvt__OakDamageComponent_K2Node_ComponentBoundEvent_0_DamageCompDiedDelegate__DelegateSignature_BPChar_ServiceBot");

	Params::BPChar_ServiceBot_C_BndEvt__OakDamageComponent_K2Node_ComponentBoundEvent_0_DamageCompDiedDelegate__DelegateSignature_BPChar_ServiceBot Parms{};

	Parms.DamageReceiver = DamageReceiver;
	Parms.DamageCauser = DamageCauser;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BPChar_ServiceBot.BPChar_ServiceBot_C.ResetTeam
// (Public, BlueprintCallable, BlueprintEvent)

void ABPChar_ServiceBot_C::ResetTeam()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPChar_ServiceBot_C", "ResetTeam");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BPChar_ServiceBot.BPChar_ServiceBot_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABPChar_ServiceBot_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPChar_ServiceBot_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BPChar_ServiceBot.BPChar_ServiceBot_C.ManageAttachedPieces
// (Public, BlueprintCallable, BlueprintEvent)

void ABPChar_ServiceBot_C::ManageAttachedPieces()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPChar_ServiceBot_C", "ManageAttachedPieces");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BPChar_ServiceBot.BPChar_ServiceBot_C.BndEvt__OakDamageComponent_K2Node_ComponentBoundEvent_1_TakeAnyPipelineHealingDelegate__DelegateSignature_BPChar_ServiceBot
// (BlueprintEvent)
// Parameters:
// class AActor*                           HealReceiver                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   Healing                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class AActor*                           HealInstigator                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABPChar_ServiceBot_C::BndEvt__OakDamageComponent_K2Node_ComponentBoundEvent_1_TakeAnyPipelineHealingDelegate__DelegateSignature_BPChar_ServiceBot(class AActor* HealReceiver, float Healing, class AActor* HealInstigator)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPChar_ServiceBot_C", "BndEvt__OakDamageComponent_K2Node_ComponentBoundEvent_1_TakeAnyPipelineHealingDelegate__DelegateSignature_BPChar_ServiceBot");

	Params::BPChar_ServiceBot_C_BndEvt__OakDamageComponent_K2Node_ComponentBoundEvent_1_TakeAnyPipelineHealingDelegate__DelegateSignature_BPChar_ServiceBot Parms{};

	Parms.HealReceiver = HealReceiver;
	Parms.Healing = Healing;
	Parms.HealInstigator = HealInstigator;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BPChar_ServiceBot.BPChar_ServiceBot_C.RegrowAttachedPiece
// (Public, BlueprintCallable, BlueprintEvent)

void ABPChar_ServiceBot_C::RegrowAttachedPiece()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPChar_ServiceBot_C", "RegrowAttachedPiece");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BPChar_ServiceBot.BPChar_ServiceBot_C.HeadDestroyed
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FDamageReactionEventSummary      DamageEventSummary                                     (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor, ContainsInstancedReference)

void ABPChar_ServiceBot_C::HeadDestroyed(const struct FDamageReactionEventSummary& DamageEventSummary)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPChar_ServiceBot_C", "HeadDestroyed");

	Params::BPChar_ServiceBot_C_HeadDestroyed Parms{};

	Parms.DamageEventSummary = std::move(DamageEventSummary);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BPChar_ServiceBot.BPChar_ServiceBot_C.RightArmDestroyed
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FDamageReactionEventSummary      DamageEventSummary                                     (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor, ContainsInstancedReference)

void ABPChar_ServiceBot_C::RightArmDestroyed(const struct FDamageReactionEventSummary& DamageEventSummary)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPChar_ServiceBot_C", "RightArmDestroyed");

	Params::BPChar_ServiceBot_C_RightArmDestroyed Parms{};

	Parms.DamageEventSummary = std::move(DamageEventSummary);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BPChar_ServiceBot.BPChar_ServiceBot_C.LeftArmDestroyed
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FDamageReactionEventSummary      DamageEventSummary                                     (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor, ContainsInstancedReference)

void ABPChar_ServiceBot_C::LeftArmDestroyed(const struct FDamageReactionEventSummary& DamageEventSummary)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPChar_ServiceBot_C", "LeftArmDestroyed");

	Params::BPChar_ServiceBot_C_LeftArmDestroyed Parms{};

	Parms.DamageEventSummary = std::move(DamageEventSummary);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BPChar_ServiceBot.BPChar_ServiceBot_C.ServiceBotLOOT_PrepareForEscape
// (Public, BlueprintCallable, BlueprintEvent)

void ABPChar_ServiceBot_C::ServiceBotLOOT_PrepareForEscape()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPChar_ServiceBot_C", "ServiceBotLOOT_PrepareForEscape");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BPChar_ServiceBot.BPChar_ServiceBot_C.ServiceBot_Drop
// (Public, BlueprintCallable, BlueprintEvent)

void ABPChar_ServiceBot_C::ServiceBot_Drop()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPChar_ServiceBot_C", "ServiceBot_Drop");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BPChar_ServiceBot.BPChar_ServiceBot_C.ServiceBot_FireExtinguisher
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    ExtinguishOn                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ABPChar_ServiceBot_C::ServiceBot_FireExtinguisher(bool ExtinguishOn)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPChar_ServiceBot_C", "ServiceBot_FireExtinguisher");

	Params::BPChar_ServiceBot_C_ServiceBot_FireExtinguisher Parms{};

	Parms.ExtinguishOn = ExtinguishOn;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BPChar_ServiceBot.BPChar_ServiceBot_C.ServiceBot_ShieldOn
// (Public, BlueprintCallable, BlueprintEvent)

void ABPChar_ServiceBot_C::ServiceBot_ShieldOn()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPChar_ServiceBot_C", "ServiceBot_ShieldOn");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BPChar_ServiceBot.BPChar_ServiceBot_C.ServiceBot_Equip_L
// (Public, BlueprintCallable, BlueprintEvent)

void ABPChar_ServiceBot_C::ServiceBot_Equip_L()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPChar_ServiceBot_C", "ServiceBot_Equip_L");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BPChar_ServiceBot.BPChar_ServiceBot_C.ManageWeapon
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    LeftWeapon                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// bool                                    HideWeapon                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ABPChar_ServiceBot_C::ManageWeapon(bool LeftWeapon, bool HideWeapon)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPChar_ServiceBot_C", "ManageWeapon");

	Params::BPChar_ServiceBot_C_ManageWeapon Parms{};

	Parms.LeftWeapon = LeftWeapon;
	Parms.HideWeapon = HideWeapon;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BPChar_ServiceBot.BPChar_ServiceBot_C.MELEE_SpawnMelee
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    SpawnRight                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ABPChar_ServiceBot_C::MELEE_SpawnMelee(bool SpawnRight)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPChar_ServiceBot_C", "MELEE_SpawnMelee");

	Params::BPChar_ServiceBot_C_MELEE_SpawnMelee Parms{};

	Parms.SpawnRight = SpawnRight;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BPChar_ServiceBot.BPChar_ServiceBot_C.EMS_ManageReviveParts
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    HasHead_0                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// bool                                    HasRightArm_0                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// bool                                    HasLeftArm_0                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ABPChar_ServiceBot_C::EMS_ManageReviveParts(bool HasHead_0, bool HasRightArm_0, bool HasLeftArm_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPChar_ServiceBot_C", "EMS_ManageReviveParts");

	Params::BPChar_ServiceBot_C_EMS_ManageReviveParts Parms{};

	Parms.HasHead_0 = HasHead_0;
	Parms.HasRightArm_0 = HasRightArm_0;
	Parms.HasLeftArm_0 = HasLeftArm_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BPChar_ServiceBot.BPChar_ServiceBot_C.WeaponFire
// (Public, BlueprintCallable, BlueprintEvent)

void ABPChar_ServiceBot_C::WeaponFire()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPChar_ServiceBot_C", "WeaponFire");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BPChar_ServiceBot.BPChar_ServiceBot_C.WeaponEffects
// (Public, BlueprintCallable, BlueprintEvent)

void ABPChar_ServiceBot_C::WeaponEffects()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPChar_ServiceBot_C", "WeaponEffects");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BPChar_ServiceBot.BPChar_ServiceBot_C.SpawnGrenade
// (Public, BlueprintCallable, BlueprintEvent)

void ABPChar_ServiceBot_C::SpawnGrenade()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPChar_ServiceBot_C", "SpawnGrenade");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BPChar_ServiceBot.BPChar_ServiceBot_C.FIRE_SpawnAxe
// (Public, BlueprintCallable, BlueprintEvent)

void ABPChar_ServiceBot_C::FIRE_SpawnAxe()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPChar_ServiceBot_C", "FIRE_SpawnAxe");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BPChar_ServiceBot.BPChar_ServiceBot_C.EMS_Defibulate
// (Public, BlueprintCallable, BlueprintEvent)

void ABPChar_ServiceBot_C::EMS_Defibulate()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPChar_ServiceBot_C", "EMS_Defibulate");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BPChar_ServiceBot.BPChar_ServiceBot_C.ThrowAttack
// (Public, BlueprintCallable, BlueprintEvent)

void ABPChar_ServiceBot_C::ThrowAttack()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPChar_ServiceBot_C", "ThrowAttack");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BPChar_ServiceBot.BPChar_ServiceBot_C.WMS_SpawnTurret
// (Public, BlueprintCallable, BlueprintEvent)

void ABPChar_ServiceBot_C::WMS_SpawnTurret()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPChar_ServiceBot_C", "WMS_SpawnTurret");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BPChar_ServiceBot.BPChar_ServiceBot_C.EMS_ManageBeam
// (Public, BlueprintCallable, BlueprintEvent)

void ABPChar_ServiceBot_C::EMS_ManageBeam()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPChar_ServiceBot_C", "EMS_ManageBeam");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BPChar_ServiceBot.BPChar_ServiceBot_C.Deactivate
// (Public, BlueprintCallable, BlueprintEvent)

void ABPChar_ServiceBot_C::Deactivate()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPChar_ServiceBot_C", "Deactivate");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BPChar_ServiceBot.BPChar_ServiceBot_C.Activate
// (Public, BlueprintCallable, BlueprintEvent)

void ABPChar_ServiceBot_C::Activate()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPChar_ServiceBot_C", "Activate");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BPChar_ServiceBot.BPChar_ServiceBot_C.OnEnd_EC6759724792DE311AC13AAA3D964D58
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// EGbxActionEndState                      EndState                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class AActor*                           Actor                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABPChar_ServiceBot_C::OnEnd_EC6759724792DE311AC13AAA3D964D58(EGbxActionEndState EndState, class AActor* Actor)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPChar_ServiceBot_C", "OnEnd_EC6759724792DE311AC13AAA3D964D58");

	Params::BPChar_ServiceBot_C_OnEnd_EC6759724792DE311AC13AAA3D964D58 Parms{};

	Parms.EndState = EndState;
	Parms.Actor = Actor;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BPChar_ServiceBot.BPChar_ServiceBot_C.OnAnimEnd_EC6759724792DE311AC13AAA3D964D58
// (BlueprintCallable, BlueprintEvent)

void ABPChar_ServiceBot_C::OnAnimEnd_EC6759724792DE311AC13AAA3D964D58()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPChar_ServiceBot_C", "OnAnimEnd_EC6759724792DE311AC13AAA3D964D58");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BPChar_ServiceBot.BPChar_ServiceBot_C.GbxAsyncRequest_Spawned_539745114742BC3F986E3EB1A4D09DFC
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class AActor*                           Actor                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   InstanceIndex                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABPChar_ServiceBot_C::GbxAsyncRequest_Spawned_539745114742BC3F986E3EB1A4D09DFC(class AActor* Actor, int32 InstanceIndex)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPChar_ServiceBot_C", "GbxAsyncRequest_Spawned_539745114742BC3F986E3EB1A4D09DFC");

	Params::BPChar_ServiceBot_C_GbxAsyncRequest_Spawned_539745114742BC3F986E3EB1A4D09DFC Parms{};

	Parms.Actor = Actor;
	Parms.InstanceIndex = InstanceIndex;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BPChar_ServiceBot.BPChar_ServiceBot_C.GbxAsyncRequest_Failed_539745114742BC3F986E3EB1A4D09DFC
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class AActor*                           Actor                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   InstanceIndex                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABPChar_ServiceBot_C::GbxAsyncRequest_Failed_539745114742BC3F986E3EB1A4D09DFC(class AActor* Actor, int32 InstanceIndex)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPChar_ServiceBot_C", "GbxAsyncRequest_Failed_539745114742BC3F986E3EB1A4D09DFC");

	Params::BPChar_ServiceBot_C_GbxAsyncRequest_Failed_539745114742BC3F986E3EB1A4D09DFC Parms{};

	Parms.Actor = Actor;
	Parms.InstanceIndex = InstanceIndex;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BPChar_ServiceBot.BPChar_ServiceBot_C.GbxAsyncRequest_Spawned_F459E0A94B14D135E2BAA09CFE31B007
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class AActor*                           Actor                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   InstanceIndex                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABPChar_ServiceBot_C::GbxAsyncRequest_Spawned_F459E0A94B14D135E2BAA09CFE31B007(class AActor* Actor, int32 InstanceIndex)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPChar_ServiceBot_C", "GbxAsyncRequest_Spawned_F459E0A94B14D135E2BAA09CFE31B007");

	Params::BPChar_ServiceBot_C_GbxAsyncRequest_Spawned_F459E0A94B14D135E2BAA09CFE31B007 Parms{};

	Parms.Actor = Actor;
	Parms.InstanceIndex = InstanceIndex;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BPChar_ServiceBot.BPChar_ServiceBot_C.GbxAsyncRequest_Failed_F459E0A94B14D135E2BAA09CFE31B007
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class AActor*                           Actor                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   InstanceIndex                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABPChar_ServiceBot_C::GbxAsyncRequest_Failed_F459E0A94B14D135E2BAA09CFE31B007(class AActor* Actor, int32 InstanceIndex)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPChar_ServiceBot_C", "GbxAsyncRequest_Failed_F459E0A94B14D135E2BAA09CFE31B007");

	Params::BPChar_ServiceBot_C_GbxAsyncRequest_Failed_F459E0A94B14D135E2BAA09CFE31B007 Parms{};

	Parms.Actor = Actor;
	Parms.InstanceIndex = InstanceIndex;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BPChar_ServiceBot.BPChar_ServiceBot_C.Shrink_To_Nothing__UpdateFunc
// (BlueprintEvent)

void ABPChar_ServiceBot_C::Shrink_To_Nothing__UpdateFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPChar_ServiceBot_C", "Shrink_To_Nothing__UpdateFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BPChar_ServiceBot.BPChar_ServiceBot_C.Shrink_To_Nothing__FinishedFunc
// (BlueprintEvent)

void ABPChar_ServiceBot_C::Shrink_To_Nothing__FinishedFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPChar_ServiceBot_C", "Shrink_To_Nothing__FinishedFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BPChar_ServiceBot.BPChar_ServiceBot_C.UserConstructionScript
// (Event, Public, BlueprintCallable, BlueprintEvent)

void ABPChar_ServiceBot_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPChar_ServiceBot_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BPChar_ServiceBot.BPChar_ServiceBot_C.IsBotInjured
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    IsInjured                                              (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ABPChar_ServiceBot_C::IsBotInjured(bool* IsInjured)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPChar_ServiceBot_C", "IsBotInjured");

	Params::BPChar_ServiceBot_C_IsBotInjured Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (IsInjured != nullptr)
		*IsInjured = Parms.IsInjured;
}


// Function BPChar_ServiceBot.BPChar_ServiceBot_C.IsEMSBot
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    IsEMS                                                  (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ABPChar_ServiceBot_C::IsEMSBot(bool* IsEMS)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPChar_ServiceBot_C", "IsEMSBot");

	Params::BPChar_ServiceBot_C_IsEMSBot Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (IsEMS != nullptr)
		*IsEMS = Parms.IsEMS;
}


// Function BPChar_ServiceBot.BPChar_ServiceBot_C.GetBotType
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// Enum_ServiceBot_Type                    BotType                                                (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABPChar_ServiceBot_C::GetBotType(Enum_ServiceBot_Type* BotType)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPChar_ServiceBot_C", "GetBotType");

	Params::BPChar_ServiceBot_C_GetBotType Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (BotType != nullptr)
		*BotType = Parms.BotType;
}


// Function BPChar_ServiceBot.BPChar_ServiceBot_C.QueryAttachedPieces
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    HasHead_0                                              (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)
// bool                                    HasRightArm_0                                          (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)
// bool                                    HasLeftArm_0                                           (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ABPChar_ServiceBot_C::QueryAttachedPieces(bool* HasHead_0, bool* HasRightArm_0, bool* HasLeftArm_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPChar_ServiceBot_C", "QueryAttachedPieces");

	Params::BPChar_ServiceBot_C_QueryAttachedPieces Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (HasHead_0 != nullptr)
		*HasHead_0 = Parms.HasHead_0;

	if (HasRightArm_0 != nullptr)
		*HasRightArm_0 = Parms.HasRightArm_0;

	if (HasLeftArm_0 != nullptr)
		*HasLeftArm_0 = Parms.HasLeftArm_0;
}


// Function BPChar_ServiceBot.BPChar_ServiceBot_C.QueryDominantPieces
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    RightArmDominant_0                                     (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)
// bool                                    LeftArmDominant_0                                      (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)
// bool                                    HeadDominant_0                                         (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ABPChar_ServiceBot_C::QueryDominantPieces(bool* RightArmDominant_0, bool* LeftArmDominant_0, bool* HeadDominant_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPChar_ServiceBot_C", "QueryDominantPieces");

	Params::BPChar_ServiceBot_C_QueryDominantPieces Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (RightArmDominant_0 != nullptr)
		*RightArmDominant_0 = Parms.RightArmDominant_0;

	if (LeftArmDominant_0 != nullptr)
		*LeftArmDominant_0 = Parms.LeftArmDominant_0;

	if (HeadDominant_0 != nullptr)
		*HeadDominant_0 = Parms.HeadDominant_0;
}


// Function BPChar_ServiceBot.BPChar_ServiceBot_C.IsLootWeaponEquipped
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    EquippedRight                                          (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)
// bool                                    EquippedLeft                                           (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ABPChar_ServiceBot_C::IsLootWeaponEquipped(bool* EquippedRight, bool* EquippedLeft)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPChar_ServiceBot_C", "IsLootWeaponEquipped");

	Params::BPChar_ServiceBot_C_IsLootWeaponEquipped Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (EquippedRight != nullptr)
		*EquippedRight = Parms.EquippedRight;

	if (EquippedLeft != nullptr)
		*EquippedLeft = Parms.EquippedLeft;
}


// Function BPChar_ServiceBot.BPChar_ServiceBot_C.ServiceBot_GetUIName
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   PlayThroughIndex                                       (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UGbxUIName*                       UIName                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABPChar_ServiceBot_C::ServiceBot_GetUIName(float PlayThroughIndex, class UGbxUIName** UIName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPChar_ServiceBot_C", "ServiceBot_GetUIName");

	Params::BPChar_ServiceBot_C_ServiceBot_GetUIName Parms{};

	Parms.PlayThroughIndex = PlayThroughIndex;

	UObject::ProcessEvent(Func, &Parms);

	if (UIName != nullptr)
		*UIName = Parms.UIName;
}

}

