#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPWeaponFireProjectileComponent_JAK_Fakobs

#include "Basic.hpp"

#include "BPWeaponFireProjectileComponent_JAK_Fakobs_classes.hpp"
#include "BPWeaponFireProjectileComponent_JAK_Fakobs_parameters.hpp"


namespace SDK
{

// Function BPWeaponFireProjectileComponent_JAK_Fakobs.BPWeaponFireProjectileComponent_JAK_Fakobs_C.ExecuteUbergraph_BPWeaponFireProjectileComponent_JAK_Fakobs
// ()
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBPWeaponFireProjectileComponent_JAK_Fakobs_C::ExecuteUbergraph_BPWeaponFireProjectileComponent_JAK_Fakobs(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPWeaponFireProjectileComponent_JAK_Fakobs_C", "ExecuteUbergraph_BPWeaponFireProjectileComponent_JAK_Fakobs");

	Params::BPWeaponFireProjectileComponent_JAK_Fakobs_C_ExecuteUbergraph_BPWeaponFireProjectileComponent_JAK_Fakobs Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BPWeaponFireProjectileComponent_JAK_Fakobs.BPWeaponFireProjectileComponent_JAK_Fakobs_C.UsedWeapon
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// uint8                                   InputChannel                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBPWeaponFireProjectileComponent_JAK_Fakobs_C::UsedWeapon(uint8 InputChannel)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPWeaponFireProjectileComponent_JAK_Fakobs_C", "UsedWeapon");

	Params::BPWeaponFireProjectileComponent_JAK_Fakobs_C_UsedWeapon Parms{};

	Parms.InputChannel = InputChannel;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BPWeaponFireProjectileComponent_JAK_Fakobs.BPWeaponFireProjectileComponent_JAK_Fakobs_C.ReceiveBeginPlay
// (Event, Public, BlueprintEvent)

void UBPWeaponFireProjectileComponent_JAK_Fakobs_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPWeaponFireProjectileComponent_JAK_Fakobs_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}

}

