#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Challenge_Collection_Journal_DesertVault2

#include "Basic.hpp"

#include "Challenge_Collection_Journal_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Challenge_Collection_Journal_DesertVault2.Challenge_Collection_Journal_DesertVault2_C
// 0x0000 (0x0340 - 0x0340)
class UChallenge_Collection_Journal_DesertVault2_C final : public UChallenge_Collection_Journal_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Challenge_Collection_Journal_DesertVault2_C">();
	}
	static class UChallenge_Collection_Journal_DesertVault2_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UChallenge_Collection_Journal_DesertVault2_C>();
	}
};
static_assert(alignof(UChallenge_Collection_Journal_DesertVault2_C) == 0x000008, "Wrong alignment on UChallenge_Collection_Journal_DesertVault2_C");
static_assert(sizeof(UChallenge_Collection_Journal_DesertVault2_C) == 0x000340, "Wrong size on UChallenge_Collection_Journal_DesertVault2_C");

}

