#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Challenge_Mission_Plot_06_OvercomeHQBlockade

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Challenge_Mission_Plot_Achievement_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Challenge_Mission_Plot_06_OvercomeHQBlockade.Challenge_Mission_Plot_06_OvercomeHQBlockade_C
// 0x0008 (0x0278 - 0x0270)
class UChallenge_Mission_Plot_06_OvercomeHQBlockade_C final : public UChallenge_Mission_Plot_Achievement_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_Challenge_Mission_Plot_06_OvercomeHQBlockade_C; // 0x0270(0x0008)(Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_Challenge_Mission_Plot_06_OvercomeHQBlockade(int32 EntryPoint);
	void CompletedChallenge(const class AGbxPlayerController* CompletedPlayer);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Challenge_Mission_Plot_06_OvercomeHQBlockade_C">();
	}
	static class UChallenge_Mission_Plot_06_OvercomeHQBlockade_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UChallenge_Mission_Plot_06_OvercomeHQBlockade_C>();
	}
};
static_assert(alignof(UChallenge_Mission_Plot_06_OvercomeHQBlockade_C) == 0x000008, "Wrong alignment on UChallenge_Mission_Plot_06_OvercomeHQBlockade_C");
static_assert(sizeof(UChallenge_Mission_Plot_06_OvercomeHQBlockade_C) == 0x000278, "Wrong size on UChallenge_Mission_Plot_06_OvercomeHQBlockade_C");
static_assert(offsetof(UChallenge_Mission_Plot_06_OvercomeHQBlockade_C, UberGraphFrame_Challenge_Mission_Plot_06_OvercomeHQBlockade_C) == 0x000270, "Member 'UChallenge_Mission_Plot_06_OvercomeHQBlockade_C::UberGraphFrame_Challenge_Mission_Plot_06_OvercomeHQBlockade_C' has a wrong offset!");

}

