#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Interface_Operative_Character

#include "Basic.hpp"

#include "CoreUObject_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Interface_Operative_Character.Interface_Operative_Character_C
// 0x0000 (0x0028 - 0x0028)
class IInterface_Operative_Character_C final : public IInterface
{
public:
	void Get_Skeletal_Mesh_Head(class UGbxSkeletalMeshComponent** Head_Mesh);
	void Get_Skeletal_Mesh_Arms(class USkeletalMeshComponent** Arms_Mesh);
	void Get_Skeletal_Mesh_Legs(class UGbxSkeletalMeshComponent** Legs);
	void Get_Skeletal_Mesh(class USkeletalMeshComponent** Skeletal_Mesh);
	void Get_Materials_Head(TArray<class UMaterialInterface*>* Materials);
	void Get_Materials_Arms(TArray<class UMaterialInterface*>* Materials);
	void Get_Materials_Legs(TArray<class UMaterialInterface*>* Materials);
	void Get_Materials_Skeletal_Mesh(TArray<class UMaterialInterface*>* Materials);
	void Get_Materials_FP_Gun(TArray<class UMaterialInterface*>* Materials);
	void Get_Materials_TP_Gun(TArray<class UMaterialInterface*>* Materials);
	void PlayerOperativeDroneSpawnAnimation();
	void HideOperativeDroneSpawnAnimation();
	void GetDroneSpawnLocation(struct FTransform* Transform);
	void BlockOperativeActionSkillActivation(bool* ShouldBlock);
	void DoOperativeCryoNovaAtLocation(const struct FVector& Location, float Damage);
	void SpawnAndThrowOperativeGrenade(class AActor* SpawnFromActor, class FName SpawnFromSocket, bool* Res, class AActor** Grenade);
	void GetOperativeShieldRemainingPercent(float* ShieldPercentRemaining);
	void GetDigiCloneShieldRemainingPercent(float* ShieldPercentRemaining);
	void GetOperativeStatusEffectOverrides(struct FCauseDamageStatusEffectOverrides* Overrides);
	void GetBarrierActionAbility(class UOakActionAbility_Barrier** Res);
	void SetOperativeDeviceVisible(bool bVisible);
	void CanActivateTrapCard(bool* Res);

	void GetDigicloneActionAbility(class UOakActionAbility_Digiclone** Res) const;
	void GetGRMLNActionAbility(class UOakActionAbility_GRMLN** Res) const;

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Interface_Operative_Character_C">();
	}
	static class IInterface_Operative_Character_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<IInterface_Operative_Character_C>();
	}
};
static_assert(alignof(IInterface_Operative_Character_C) == 0x000008, "Wrong alignment on IInterface_Operative_Character_C");
static_assert(sizeof(IInterface_Operative_Character_C) == 0x000028, "Wrong size on IInterface_Operative_Character_C");

}

