#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: LightProjectile_Disruptor

#include "Basic.hpp"

#include "LightProjectile_JAK_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass LightProjectile_Disruptor.LightProjectile_Disruptor_C
// 0x0000 (0x0490 - 0x0490)
class ULightProjectile_Disruptor_C final : public ULightProjectile_JAK_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"LightProjectile_Disruptor_C">();
	}
	static class ULightProjectile_Disruptor_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ULightProjectile_Disruptor_C>();
	}
};
static_assert(alignof(ULightProjectile_Disruptor_C) == 0x000010, "Wrong alignment on ULightProjectile_Disruptor_C");
static_assert(sizeof(ULightProjectile_Disruptor_C) == 0x000490, "Wrong size on ULightProjectile_Disruptor_C");

}

