#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: LightProjectile_DoUntoOthers

#include "Basic.hpp"

#include "LightProjectile_DoUntoOthers_classes.hpp"
#include "LightProjectile_DoUntoOthers_parameters.hpp"


namespace SDK
{

// Function LightProjectile_DoUntoOthers.LightProjectile_DoUntoOthers_C.EnableProjectileHoming
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UOakLightProjectile*              LightProjectile                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ULightProjectile_DoUntoOthers_C::EnableProjectileHoming(class UOakLightProjectile* LightProjectile)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LightProjectile_DoUntoOthers_C", "EnableProjectileHoming");

	Params::LightProjectile_DoUntoOthers_C_EnableProjectileHoming Parms{};

	Parms.LightProjectile = LightProjectile;

	UObject::ProcessEvent(Func, &Parms);
}


// Function LightProjectile_DoUntoOthers.LightProjectile_DoUntoOthers_C.TryEnableProjectileHoming
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UOakLightProjectile*              Projectile                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ULightProjectile_DoUntoOthers_C::TryEnableProjectileHoming(class UOakLightProjectile* Projectile)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LightProjectile_DoUntoOthers_C", "TryEnableProjectileHoming");

	Params::LightProjectile_DoUntoOthers_C_TryEnableProjectileHoming Parms{};

	Parms.Projectile = Projectile;

	UObject::ProcessEvent(Func, &Parms);
}


// Function LightProjectile_DoUntoOthers.LightProjectile_DoUntoOthers_C.OnLifetimeExpired
// (Event, Public, BlueprintCallable, BlueprintEvent, Const)
// Parameters:
// class ULightProjectile*                 Projectile                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ULightProjectile_DoUntoOthers_C::OnLifetimeExpired(class ULightProjectile* Projectile) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LightProjectile_DoUntoOthers_C", "OnLifetimeExpired");

	Params::LightProjectile_DoUntoOthers_C_OnLifetimeExpired Parms{};

	Parms.Projectile = Projectile;

	UObject::ProcessEvent(Func, &Parms);
}

}

