#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ShieldAug_Wattson

#include "Basic.hpp"

#include "ShieldAug_Wattson_classes.hpp"
#include "ShieldAug_Wattson_parameters.hpp"


namespace SDK
{

// Function ShieldAug_Wattson.ShieldAug_Wattson_C.K2_OnDamageTaken
// (Event, Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, Const)
// Parameters:
// class AShield*                          Shield                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FAugmentData                     StackData                                              (BlueprintVisible, Parm, OutParm, ReferenceParm, NoDestructor)
// class UDamageComponent*                 DamageReceiver                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   Damage                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UGbxDamageType*                   DamageType                                             (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UDamageSource*                    DamageSource                                           (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class AController*                      InstigatedBy                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UDamageCauserComponent*           DamageCauser                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FReceivedDamageDetails           Details                                                (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, ContainsInstancedReference)

void UShieldAug_Wattson_C::K2_OnDamageTaken(class AShield* Shield, struct FAugmentData& StackData, class UDamageComponent* DamageReceiver, float Damage, const class UGbxDamageType* DamageType, const class UDamageSource* DamageSource, class AController* InstigatedBy, class UDamageCauserComponent* DamageCauser, const struct FReceivedDamageDetails& Details) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ShieldAug_Wattson_C", "K2_OnDamageTaken");

	Params::ShieldAug_Wattson_C_K2_OnDamageTaken Parms{};

	Parms.Shield = Shield;
	Parms.StackData = std::move(StackData);
	Parms.DamageReceiver = DamageReceiver;
	Parms.Damage = Damage;
	Parms.DamageType = DamageType;
	Parms.DamageSource = DamageSource;
	Parms.InstigatedBy = InstigatedBy;
	Parms.DamageCauser = DamageCauser;
	Parms.Details = std::move(Details);

	UObject::ProcessEvent(Func, &Parms);

	StackData = std::move(Parms.StackData);
}


// Function ShieldAug_Wattson.ShieldAug_Wattson_C.K2_OnShieldDepleted
// (Event, Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, Const)
// Parameters:
// class AShield*                          Shield                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FGameResourcePoolReference       ResourcePool                                           (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor, ContainsInstancedReference)
// struct FAugmentData                     StackData                                              (BlueprintVisible, Parm, OutParm, ReferenceParm, NoDestructor)

void UShieldAug_Wattson_C::K2_OnShieldDepleted(class AShield* Shield, const struct FGameResourcePoolReference& ResourcePool, struct FAugmentData& StackData) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ShieldAug_Wattson_C", "K2_OnShieldDepleted");

	Params::ShieldAug_Wattson_C_K2_OnShieldDepleted Parms{};

	Parms.Shield = Shield;
	Parms.ResourcePool = std::move(ResourcePool);
	Parms.StackData = std::move(StackData);

	UObject::ProcessEvent(Func, &Parms);

	StackData = std::move(Parms.StackData);
}


// Function ShieldAug_Wattson.ShieldAug_Wattson_C.K2_OnShieldFilled
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent, Const)
// Parameters:
// class AShield*                          Shield                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FGameResourcePoolReference       ResourcePool                                           (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor, ContainsInstancedReference)
// struct FAugmentData                     StackData                                              (BlueprintVisible, Parm, OutParm, ReferenceParm, NoDestructor)

void UShieldAug_Wattson_C::K2_OnShieldFilled(class AShield* Shield, const struct FGameResourcePoolReference& ResourcePool, struct FAugmentData& StackData) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ShieldAug_Wattson_C", "K2_OnShieldFilled");

	Params::ShieldAug_Wattson_C_K2_OnShieldFilled Parms{};

	Parms.Shield = Shield;
	Parms.ResourcePool = std::move(ResourcePool);
	Parms.StackData = std::move(StackData);

	UObject::ProcessEvent(Func, &Parms);

	StackData = std::move(Parms.StackData);
}

}

