#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: StandIn_Beastmaster_Spiderant

#include "Basic.hpp"

#include "StandIn_Beastmaster_Spiderant_classes.hpp"


namespace SDK
{

// Function StandIn_Beastmaster_Spiderant.StandIn_Beastmaster_Spiderant_C.UserConstructionScript
// (Event, Public, BlueprintCallable, BlueprintEvent)

void AStandIn_Beastmaster_Spiderant_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("StandIn_Beastmaster_Spiderant_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}

}

