#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_GRP_TTR_Opt_BG

#include "Basic.hpp"

#include "WBP_GRP_TTR_Opt_BG_classes.hpp"
#include "WBP_GRP_TTR_Opt_BG_parameters.hpp"


namespace SDK
{

// Function WBP_GRP_TTR_Opt_BG.WBP_GRP_TTR_Opt_BG_C.ExecuteUbergraph_WBP_GRP_TTR_Opt_BG
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_GRP_TTR_Opt_BG_C::ExecuteUbergraph_WBP_GRP_TTR_Opt_BG(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_GRP_TTR_Opt_BG_C", "ExecuteUbergraph_WBP_GRP_TTR_Opt_BG");

	Params::WBP_GRP_TTR_Opt_BG_C_ExecuteUbergraph_WBP_GRP_TTR_Opt_BG Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_GRP_TTR_Opt_BG.WBP_GRP_TTR_Opt_BG_C.OnChange_Brightness
// (Event, Public, BlueprintEvent)

void UWBP_GRP_TTR_Opt_BG_C::OnChange_Brightness()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_GRP_TTR_Opt_BG_C", "OnChange_Brightness");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_GRP_TTR_Opt_BG.WBP_GRP_TTR_Opt_BG_C.OnChange_Normal
// (Event, Public, BlueprintEvent)

void UWBP_GRP_TTR_Opt_BG_C::OnChange_Normal()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_GRP_TTR_Opt_BG_C", "OnChange_Normal");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_GRP_TTR_Opt_BG.WBP_GRP_TTR_Opt_BG_C.OnHideStarted
// (Event, Public, BlueprintEvent)

void UWBP_GRP_TTR_Opt_BG_C::OnHideStarted()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_GRP_TTR_Opt_BG_C", "OnHideStarted");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_GRP_TTR_Opt_BG.WBP_GRP_TTR_Opt_BG_C.OnShowFinished
// (Event, Public, BlueprintEvent)

void UWBP_GRP_TTR_Opt_BG_C::OnShowFinished()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_GRP_TTR_Opt_BG_C", "OnShowFinished");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_GRP_TTR_Opt_BG.WBP_GRP_TTR_Opt_BG_C.OnShowStarted
// (Event, Public, BlueprintEvent)

void UWBP_GRP_TTR_Opt_BG_C::OnShowStarted()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_GRP_TTR_Opt_BG_C", "OnShowStarted");

	UObject::ProcessEvent(Func, nullptr);
}

}

