#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_GRP_SpecialGaugeSet_P1

#include "Basic.hpp"

#include "WBP_GRP_SpecialGaugeSet_P1_classes.hpp"
#include "WBP_GRP_SpecialGaugeSet_P1_parameters.hpp"


namespace SDK
{

// Function WBP_GRP_SpecialGaugeSet_P1.WBP_GRP_SpecialGaugeSet_P1_C.ExecuteUbergraph_WBP_GRP_SpecialGaugeSet_P1
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_GRP_SpecialGaugeSet_P1_C::ExecuteUbergraph_WBP_GRP_SpecialGaugeSet_P1(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_GRP_SpecialGaugeSet_P1_C", "ExecuteUbergraph_WBP_GRP_SpecialGaugeSet_P1");

	Params::WBP_GRP_SpecialGaugeSet_P1_C_ExecuteUbergraph_WBP_GRP_SpecialGaugeSet_P1 Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_GRP_SpecialGaugeSet_P1.WBP_GRP_SpecialGaugeSet_P1_C.OnChangeChargeStarted
// (Event, Public, BlueprintEvent)

void UWBP_GRP_SpecialGaugeSet_P1_C::OnChangeChargeStarted()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_GRP_SpecialGaugeSet_P1_C", "OnChangeChargeStarted");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_GRP_SpecialGaugeSet_P1.WBP_GRP_SpecialGaugeSet_P1_C.OnChangeNormalFinished
// (Event, Public, BlueprintEvent)

void UWBP_GRP_SpecialGaugeSet_P1_C::OnChangeNormalFinished()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_GRP_SpecialGaugeSet_P1_C", "OnChangeNormalFinished");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_GRP_SpecialGaugeSet_P1.WBP_GRP_SpecialGaugeSet_P1_C.OnChangeNormalStarted
// (Event, Public, BlueprintEvent)

void UWBP_GRP_SpecialGaugeSet_P1_C::OnChangeNormalStarted()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_GRP_SpecialGaugeSet_P1_C", "OnChangeNormalStarted");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_GRP_SpecialGaugeSet_P1.WBP_GRP_SpecialGaugeSet_P1_C.OnChangeSparkingFinished
// (Event, Public, BlueprintEvent)

void UWBP_GRP_SpecialGaugeSet_P1_C::OnChangeSparkingFinished()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_GRP_SpecialGaugeSet_P1_C", "OnChangeSparkingFinished");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_GRP_SpecialGaugeSet_P1.WBP_GRP_SpecialGaugeSet_P1_C.OnChangeSparkingStarted
// (Event, Public, BlueprintEvent)

void UWBP_GRP_SpecialGaugeSet_P1_C::OnChangeSparkingStarted()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_GRP_SpecialGaugeSet_P1_C", "OnChangeSparkingStarted");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_GRP_SpecialGaugeSet_P1.WBP_GRP_SpecialGaugeSet_P1_C.OnHideStarted
// (Event, Public, BlueprintEvent)

void UWBP_GRP_SpecialGaugeSet_P1_C::OnHideStarted()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_GRP_SpecialGaugeSet_P1_C", "OnHideStarted");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_GRP_SpecialGaugeSet_P1.WBP_GRP_SpecialGaugeSet_P1_C.OnShowStarted
// (Event, Public, BlueprintEvent)

void UWBP_GRP_SpecialGaugeSet_P1_C::OnShowStarted()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_GRP_SpecialGaugeSet_P1_C", "OnShowStarted");

	UObject::ProcessEvent(Func, nullptr);
}

}

